// src/react/components/home-section/landing-page1/service/index.js
import React from 'react';

import { SectionTitle,SectionStyle3, CardStyle13 } from '../../../xamin';


class Index extends React.Component {

    constructor(props) {
        super(props);

        this.state = {
            cardData: [
                {
                    images:  require('../../../../public/assets/images/testimonials/3.jpg'),
                    name: "Mark McManus",
                    position: "COO",
                    description: "“Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.” ",
                },
                {
                    images:  require('../../../../public/assets/images/testimonials/2.jpg'),
                    name: "Jack White",
                    position: "CEO",
                    description: "“Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.” ",
                },
                {
                    images:  require('../../../../public/assets/images/testimonials/3.jpg'),
                    name: "Jack McManus",
                    position: "CTO",
                    description: "“Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.” ",
                }
               
            ]
        }

    }

    render() {
        let { cardData } = this.state;
        return (
            <>
                <SectionStyle3 id="our-service" >
                <div className="row">
                     <div className="col-sm-12 wow fadeInUp">
                        <SectionTitle
                                link="OUR SERVICES"
                                className = "title-box wow fadeInUp text-center"
                                title="What Our Clients Say"
                                spanclass="title-design"
                        />
                    </div>
                </div>
                <div className="row">
                    <div className="col-md-12  wow fadeInUp">
                            <div className="owl-carousel testimonial-style owl-loaded owl-drag" data-dots="true" data-nav="false" data-autoplay="false" data-loop="true" data-items="1" data-items-laptop="1" data-items-tab="1" data-items-mobile="1" data-items-mobile-sm="1" data-margin="30">
                                {
                                    cardData.map((card, index) => (
                                        <CardStyle13
                                            key={index}
                                            image={card.images}
                                            title={card.name}
                                            subTitle={card.position}
                                            description={card.description}
                                        />
                                    ))
                                }
                            </div>
                    </div>
               </div>

                </SectionStyle3>
            </>
        );
    }

}

export default Index;

// src/vue/components/BigDataServices/Service.vue
<template>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-sm-12 sidebar-service-left">
          <CardStyle5 :card-menu="menu_item" />
          <div class="testimonial-widget-menu widget">
            <CardStyle3 :card-content="list" card-class="owl-carousel owl-loaded owl-drag"/>
          </div>
          <div class="widget get-file">
            <h2 class="widget-title">Downloads</h2>
            <a href="#">
              <ul class="list-inline download-item">
                <li class="list-inline-item"> <i class="far fa-file-pdf"></i><span class="ml-3">PDF download</span> </li>
              </ul>
            </a>
          </div>
          <div class="widget get-file mb-5">
            <a href="#">
              <ul class="list-inline download-item">
                <li class="list-inline-item"><i class="far fa-file-pdf"></i><span class="ml-3">Company White Paper</span></li>
              </ul>
            </a>
          </div>
        </div>
        <div class="col-lg-8 col-sm-12">
          <h3 class="text-left mb-2">Big Data Consulting</h3>
          <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable. It uses a dictionary of over 200 Latin words.</p>
          <p class="mb-5">All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.</p>
          <div class="row iq-pb-45">
            <div class="col-md-12">
              <div class="owl-carousel owl-services owl-loaded owl-drag"
                data-dots="false"
                data-nav="false"
                data-items="2"
                data-items-laptop="1"
                data-items-tab="1"
                data-items-mobile="1"
                data-items-mobile-sm="1"
                data-autoplay="true"
                data-loop="true"
                data-margin="15"
                >
                <div v-for="(item,index) in images" :key="index" class="Consulting-box service-slider  text-left">
                    <img :src="item.src" alt="slider">
                    <div class="details-box clearfix">
                      <div class="consult-details">
                          <h5>{{ item.title }}</h5>
                          <p class="mb-0">{{ item.subtitle }}</p>
                      </div>
                      <a href="#"><i aria-hidden="true" class="ion ion-plus"></i></a>
                    </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
                <h3 class="text-left mb-2">Big Data Implementation</h3>
                <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn’t anything embarrassing hidden .</p>
                <p>All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.</p>
            </div>
          </div>
          <div class="row iq-pb-45">
            <div class="col-md-6">
                <h4 class="text-left mb-4">Big data support</h4>
                <div class="text-left">
                  <ul class="iq-list">
                      <li><i class="fas fa-check-square"></i><span>Simply dummy text of the Lorem Ipsum.</span></li>
                      <li><i class="fas fa-check-square"></i><span>There are many variations of passages.</span></li>
                      <li><i class="fas fa-check-square"></i><span>Contrary to popular belief, Lorem </span></li>
                      <li><i class="fas fa-check-square"></i><span>It is a long established fact that a reader.</span></li>
                      <li><i class="fas fa-check-square"></i><span>All the Lorem Ipsum generators.</span></li>
                  </ul>
                </div>
            </div>
            <div class="col-md-6 iq-sm-mt-30">
                <h4 class="text-left mb-4">Big data managed</h4>
                <div class="wrapper">
                  <div class="service-chart">
                      <canvas id="canvas" class="big-data-services-chart" width="216" height="216"></canvas>
                  </div>
                  <ul id="js-legend" class="chart-legend"></ul>
                </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
                <h3 class="text-left mb-2">Data Implementation</h3>
                <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn’t anything embarrassing hidden.</p>
                <p class="mb-0">All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
import CardStyle3 from '../themes/Card/CardStyle3.vue';
import CardStyle5 from '../themes/Card/CardStyle5.vue';
export default {
  name: 'Service',
  components: {
    CardStyle3,
    CardStyle5
  },
  data() {
    return {
      list:[
        {
          title: 'Jack White',
          subtitle: 'CEO',
          description: 'Richard McClintock, a Latin professor at Hampden-Sydney consectetur adip isicing elit, sed dolore magna aliqua hampden. Latin professor at Hampden-Sydney consectetur.',
          src: '/assets/images/testimonials/1.jpg'
        },
        {
          title: 'Walhan Bobe',
          subtitle: 'Business Adviser',
          description: '“Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium incididunt ut labore et dolore Sed ut perspiciatis error. Perspiciatis unde omnis iste.”',
          src: '/assets/images/testimonials/2.jpg'
        },
        {
          title: 'Mark McManus',
          subtitle: 'COO',
          description: '“Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.”',
          src: '/assets/images/testimonials/3.jpg'
        }
      ],
      images: [
        {
          title: 'Apache Hadoop',
          subtitle: 'It is a long established.',
          src: '/assets/images/about-us/03.png'
        },
        {
          title: 'Apache Spark',
          subtitle: 'It is a long established.',
          src: '/assets/images/about-us/04.png'
        },
        {
          title: 'Apache Cassandra',
          subtitle: 'It is a long established.',
          src: '/assets/images/about-us/05.png'
        },
        {
          title: 'Big Data Consulting',
          subtitle: 'It is a long established.',
          src: '/assets/images/about-us/04.png'
        }
      ],
      menu_item: [
        {
          title: 'Data Analytics',
          class: 'nav-link',
          href: 'data-analytics'
        },
        {
          title: 'Managed Analytics',
          class: 'nav-link',
          href: 'managed-analytics'
        },
        {
          title: 'Big Data Services',
          class: 'nav-link current-menu-item',
          href: 'big-data-services'
        },
        {
          title: 'Data Science Consulting',
          class: 'nav-link',
          href: 'data-science-consulting'
        },
        {
          title: 'Business Intelligence',
          class: 'nav-link',
          href: 'business-intelligence'
        },
        {
          title: 'Data Visualization',
          class: 'nav-link',
          href: 'data-visualization'
        },
        {
          title: 'Data Management',
          class: 'nav-link',
          href: 'data-management'
        },
        {
          title: 'Artificial Intelligence',
          class: 'nav-link',
          href: 'artificial-intelligence'
        }
      ]
    }
  }
}
</script>
