// src/react/components/home-section/landing-page1/awards/index.js
import React from 'react';

import { SectionTitle,SectionStyle3 } from '../../../xamin';
import Image from 'next/image';

const Cards = (props) => {
    const cardList = props.cardList;
    return cardList.map((card, index) => (
        <div key={index}  className="col-md-3">
            <div className="xamin-award wow fadeInUp  text-center">
                <div className="award-img"> <Image src={card.img} alt='award-imgs'/> </div>
                <h5 className="mt-3">{card.desc}</h5>
             </div>
        </div>
           
    ));
};

class Index extends React.Component {

    constructor(props) {
        super(props);

        this.state = {
            cardData: [
                {
                    img:  require('../../../../public/assets/images/awards/1.png'),
                    desc: "Microsoft Partner of the Year Award",
                },
                {
                    img:  require('../../../../public/assets/images/awards/2.png'),
                    desc: "Global Sourcing Awards 2018 Finalist",
                },
                {
                    img:  require('../../../../public/assets/images/awards/4.png'),
                    desc: "Gold Winner of 2013 Horizon Awards",
                },  
                {
                    img:  require('../../../../public/assets/images/awards/3.png'),
                    desc: "European Software Testing Awards Finalist",
                },
                {
                    img:  require('../../../../public/assets/images/awards/5.png'),
                    desc: "Microsoft Partner of the Year Award",
                },
                {
                    img:  require('../../../../public/assets/images/awards/3.png'),
                    desc: "Global Sourcing Awards 2018 Finalist",
                },
                {
                    img:  require('../../../../public/assets/images/awards/2.png'),
                    desc: "Gold Winner of 2013 Horizon Awards",
                }
               
            ]
        }

    }

    render() {

        return (
            <>
                <SectionStyle3 >
                <div className="row">
                     <div className="col-sm-12 wow fadeInUp">
                        <SectionTitle
                                link="AWARDS"
                                className = "title-box wow fadeInUp text-center"
                                title="Awards & Accreditations"
                                subTitle="It is a long established fact that a reader will be distracted by the readable"
                                spanclass="title-design"
                        />
                    </div>
                </div>
                <div className="row wow fadeInUp justify-content-center">
                        <Cards cardList={this.state.cardData} />
               </div>

                </SectionStyle3>
            </>
        );
    }

}

export default Index;

// src/vue/components/LandingPage17/Awards.vue
<template>
  <section class="pt-0 iq-pb-55">
    <div class="container">
      <div class="row">
        <div class="col-md-12 wow fadeInUp title-box text-center">
          <span class="title-design">Awards</span>
          <h2>Awards &amp; Accreditations</h2>
          <p class="mb-0">
            It is a long established fact that a reader will be distracted by the readable
          </p>
        </div>
      </div>
      <div class="row wow fadeInUp mb-5">
        <div v-for="(option,index) in images1" :key="index" class="col-md-3">
          <div class="xamin-award wow fadeInUp  text-center">
            <div class="award-img">
              <img :src="option.src" alt="fancybox">
            </div>
            <h5 class="mt-3">
              {{ option.title }}
            </h5>
          </div>
        </div>
      </div>
      <div class="row wow fadeInUp offset-lg-2">
        <div v-for="(option,index) in images2" :key="index" class="col-lg-3 col-md-4">
          <div class="xamin-award wow fadeInUp text-center">
            <div class="award-img">
              <img :src="option.src" alt="fancybox">
            </div>
            <h5 class="mt-3">
              {{ option.title }}
            </h5>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {
  name: 'Awards',
  data () {
    return {
      images1: [
        {
          title: 'Microsoft Partner of the Year Award',
          src: '/assets/images/awards/1.png'
        },
        {
          title: 'Gold Winner of 2013 Horizon Awards',
          src: '/assets/images/awards/2.png'
        },
        {
          title: 'Global Sourcing Awards 2018 Finalist',
          src: '/assets/images/awards/3.png'
        },
        {
          title: 'European Software Testing Awards Finalist',
          src: '/assets/images/awards/4.png'
        }
      ],
      images2: [
        {
          title: 'Microsoft Partner of the Year Award',
          src: '/assets/images/awards/1.png'
        },
        {
          title: 'Gold Winner of 2013 Horizon Awards',
          src: '/assets/images/awards/2.png'
        },
        {
          title: 'Global Sourcing Awards 2018 Finalist',
          src: '/assets/images/awards/3.png'
        }
      ]
    }
  }
}
</script>
