// src/vue/components/LandingPage6/Partner.vue
<template>
  <section class="pt-0">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="owl-carousel owl-loaded owl-drag"
              data-dots="false"
              data-nav="false"
              data-items="6"
              data-items-laptop="4"
              data-items-tab="3"
              data-items-mobile="2"
              data-items-mobile-sm="1"
              data-dots-mobile="true"
              data-autoplay="true"
              data-loop="true"
              data-margin="30"
              >
              <div class="item">
                  <div class="clients-box">
                      <img class="img-fluid client-img" src="/assets/images/partners/1.png" alt="image0">
                  </div>
              </div>
              <div class="item">
                  <div class="clients-box">
                      <img class="img-fluid client-img" src="/assets/images/partners/2.png" alt="image1">
                  </div>
              </div>
              <div class="item">
                  <div class="clients-box">
                      <img class="img-fluid client-img" src="/assets/images/partners/3.png" alt="image2">
                  </div>
              </div>
              <div class="item">
                  <div class="clients-box">
                      <img class="img-fluid client-img" src="/assets/images/partners/4.png" alt="image3">
                  </div>
              </div>
              <div class="item">
                  <div class="clients-box">
                      <img class="img-fluid client-img" src="/assets/images/partners/5.png" alt="image4">
                  </div>
              </div>
              <div class="item">
                  <div class="clients-box">
                      <img class="img-fluid client-img" src="/assets/images/partners/1.png" alt="image5">
                  </div>
              </div>
              <div class="item">
                  <div class="clients-box">
                      <img class="img-fluid client-img" src="/assets/images/partners/2.png" alt="image6">
                  </div>
              </div>
              <div class="item">
                  <div class="clients-box">
                      <img class="img-fluid client-img" src="/assets/images/partners/3.png" alt="image7">
                  </div>
              </div>
              <div class="item">
                  <div class="clients-box">
                      <img class="img-fluid client-img" src="/assets/images/partners/4.png" alt="image8">
                  </div>
              </div>
              <div class="item">
                  <div class="clients-box">
                      <img class="img-fluid client-img" src="/assets/images/partners/5.png" alt="image9">
                  </div>
              </div>
              <div class="item">
                  <div class="clients-box">
                      <img class="img-fluid client-img" src="/assets/images/partners/1.png" alt="image10">
                  </div>
              </div>
              <div class="item">
                  <div class="clients-box">
                      <img class="img-fluid client-img" src="/assets/images/partners/2.png" alt="image11">
                  </div>
              </div>
              <div class="item">
                  <div class="clients-box">
                      <img class="img-fluid client-img" src="/assets/images/partners/3.png" alt="image12">
                  </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {
  name:'Partner'
}
</script>

// src/react/components/home-section/landing-page4/partner/index.js
import React from 'react';

import { SectionTitle,Carousel } from '../../../xamin';
import Image from 'next/image';

const Carousel1 = (props) => {
    const cardList = props.cardList;
    return cardList.map((card, index) => (
                <div  key={index} className="item">
                    <div className="clients-box">
                        <Image alt="#" className="img-fluid client-img" src={card.img} />
                    </div>
                </div>
    ));
};


class Index extends React.Component {

    constructor(props) {
        super(props);

        this.state = {
            cardData1: [
                {
                    img:  require('../../../../public/assets/images/partners/1.png'),
                   
                },
                {
                    img:  require('../../../../public/assets/images/partners/2.png'),
                    
                },
                {
                    img:  require('../../../../public/assets/images/partners/3.png'),
                    
                },
                {
                    img:  require('../../../../public/assets/images/partners/4.png'),
                    
                },
                {
                    img:  require('../../../../public/assets/images/partners/5.png'),
                    
                }
            ],
           
        }

    }

    render() {

        return (
            <>
                <section className="iq-bg-over">
                    <div className="container">
                        <div className="row">
                            <div className="col-md-12">
                                <div className="owl-carousel owl-loaded owl-drag"
                                    data-dots="false"
                                    data-nav="false"
                                    data-items="6"
                                    data-items-laptop="4"
                                    data-items-tab="3"
                                    data-items-mobile="2"
                                    data-items-mobile-sm="1"
                                    data-autoplay="true"
                                    data-loop="true"
                                    data-margin="30"
                                >
                                        { this.state.cardData1.map((item, index) => (
                                                <Carousel
                                                    key={index}
                                                    img ={item.img}
                                                    imgClass ="img-fluid client-img"
                                                />
                                        )) }
                                </div>
                            </div>
                        </div>
                        
               </div>
                </section>
            </>
        );
    }

}

export default Index;
