// src/react/components/xamin/Loader/index.js
import Image from 'next/image';
import React from 'react'

import loader from "../../../public/assets/images/loader.gif"

const Index = () => (
    <div id="loading">
        <div id="loading-center">
            <Image src={loader} alt="loader" />
        </div>
    </div>
);

export default Index;

// src/vue/components/themes/Loader.vue
<template>
  <div id="loading">
    <div class="loading-center">
      <img src="/assets/images/loader.gif" alt="loader" />
    </div>
  </div>
</template>
<script>
import * as $ from "jquery";
export default {
  name: "Loader",
  watch: {
    $route(to, from) {
      $("#loading").show();
      setTimeout(() => {
        $("#loading").delay(1000).fadeOut("slow");
      }, 100);
    },
  },
};
</script>
