// src/react/components/xamin/ScrollTop/index.js
import React from 'react';
import $ from 'jquery';
import Link from 'next/link';

const scrollTop = () => {
    $('body,html').animate({
        scrollTop: 0
    }, 800);
};
const Index = () => {

    return (
        <>
            <div id="back-to-top" style={{ display: 'none' }}>
                <Link className="top" id="top" href="#" onClick={scrollTop}> <i className="fa fa-chevron-up" /> </Link>
            </div>
        </>
    );
};

export default Index;

// src/vue/components/themes/ScrollTop.vue
<template>
  <div id="back-to-top" style="display: none;">
    <a id="top" href="#" class="top" @click="scrollTop()"> <i class="ion-ios-arrow-up" /> </a>
  </div>
</template>
<script>
export default {
  name: 'ScrollTop',
  methods: {
    scrollTop () {
      window.jQuery('body,html').animate({
        scrollTop: 0
      }, 800)
    }
  }
}
</script>
