// src/react/components/about-section/about-us2/services/index.js
import React from 'react';
import { CardStyle8, CheckboxList, SectionTitle } from '../../../xamin';

class Index extends React.Component {
    constructor(props) {
        super(props);
        this.state={
            cards:[
                {
                    image:require("../../../../public/assets/images/services/01.png"),
                    title:'Data Analytics',
                    description:'It is a long established fact that a reader will be distracted by the of readable content.',
                    checklist:[
                        'Advance Advisory Team',
                        'Professional Consulting Services',
                        'Advance Advisory Team'
                    ]
                },
                {
                    image:require("../../../../public/assets/images/services/02.png"),
                    title:'Managed Analytics',
                    description:'It is a long established fact that a reader will be distracted by the of readable content.',
                    checklist:[
                        'Advance Advisory Team',
                        'Professional Consulting Services',
                        'Advance Advisory Team'
                    ]
                },
                {
                    image:require("../../../../public/assets/images/services/03.png"),
                    title:'Big Data Services',
                    description:'It is a long established fact that a reader will be distracted by the of readable content.',
                    checklist:[
                        'Advance Advisory Team',
                        'Professional Consulting Services',
                        'Advance Advisory Team'
                    ]
                },
                {
                    image:require("../../../../public/assets/images/services/01.png"),
                    title:'Data Science',
                    description:'It is a long established fact that a reader will be distracted by the of readable content.',
                    checklist:[
                        'Advance Advisory Team',
                        'Professional Consulting Services',
                        'Advance Advisory Team'
                    ]
                },
                {
                    image:require("../../../../public/assets/images/services/02.png"),
                    title:'Business Intelligence',
                    description:'It is a long established fact that a reader will be distracted by the of readable content.',
                    checklist:[
                        'Advance Advisory Team',
                        'Professional Consulting Services',
                        'Advance Advisory Team'
                    ]
                },
                {
                    image:require("../../../../public/assets/images/services/03.png"),
                    title:'Data Visualization',
                    description:'It is a long established fact that a reader will be distracted by the of readable content.',
                    checklist:[
                        'Advance Advisory Team',
                        'Professional Consulting Services',
                        'Advance Advisory Team'
                    ]
                },
            ]
        }
    }
    render() {
        let { cards } = this.state;
        return (
            <>
               <section>
                   <div className="container">
                       <div className="row">
                           <div className="col-lg-12">
                               <SectionTitle
                                   className="title-box text-center"
                                   spanclass="title-design"
                                   link="our Services"
                                   title="We Provide Useful Services"
                               />
                           </div>
                           {
                               cards.map((item,index) => (
                                   <div key={'s1'+index} className={"col-lg-4 col-md-6"}>
                                       <CardStyle8
                                           image={item.image}
                                           title={item.title}
                                           description={item.description}
                                           className="text-left"
                                       >
                                            <CheckboxList text="text-center text-md-left" items={item.checklist} />
                                       </CardStyle8>
                                   </div>
                               ))
                           }
                       </div>
                   </div>
               </section>
            </>
        );
    }
}

export default Index;

// src/vue/components/AboutUs-2/Services.vue
<template>
  <section class="aboutus-two-service">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="title-box wow fadeInUp text-center">
            <span class="title-design">Our Services</span>
            <h2>We Provide Useful Services</h2>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 col-md-6" v-for="(list,index) in items" :key="index">
          <CardStyle1>
            <template #cardMedia>
              <div>
              <img :src="list.src" alt="fancy-list">
            </div>
            </template>
            <template #cardTitle>
              <div>
              <h4 class="mb-2">{{ list.title }}</h4>
            </div>
            </template>
            <template #cardBody>
              <div>
              <p>{{ list.description }}</p>
            </div>
            </template>
            <template #cardList>
              <div class="text-left">
              <ul class="iq-list">
                <li> <i class="fas fa-check-square"></i><span>Advance Advisory Team</span> </li>
                <li> <i class="fas fa-check-square"></i><span>Professional Consulting Services</span> </li>
                <li> <i class="fas fa-check-square"></i><span>Advance Advisory Team</span> </li>
              </ul>
            </div>
            </template>
          </CardStyle1>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
import CardStyle1 from '../themes/Card/CardStyle1' 
export default {
  name: 'Services',
  components: { CardStyle1 },
  data() {
    return{
      items : [
        {
          title: 'Data Analytics',
          description: 'It is a long established fact that a reader will be distracted by the of readable content.',
          src: '/assets/images/services/01.png'
        },
        {
          title: 'Managed Analytics',
          description: 'It is a long established fact that a reader will be distracted by the of readable content.',
          src: '/assets/images/services/02.png'
        },
        {
          title: 'Big Data Services',
          description: 'It is a long established fact that a reader will be distracted by the of readable content.',
          src: '/assets/images/services/03.png'
        },
        {
          title: 'Data Science',
          description: 'It is a long established fact that a reader will be distracted by the of readable content.',
          src: '/assets/images/services/04.png'
        },
        {
          title: 'Business Intelligence',
          description: 'It is a long established fact that a reader will be distracted by the of readable content.',
          src: '/assets/images/services/05.png'
        },
        {
          title: 'Data Visualization',
          description: 'It is a long established fact that a reader will be distracted by the of readable content.',
          src: '/assets/images/services/06.png'
        }
      ]
    }
  }
}
</script>
