// src/vue/components/AboutUs-2/Services.vue
<template>
  <section class="aboutus-two-service">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="title-box wow fadeInUp text-center">
            <span class="title-design">Our Services</span>
            <h2>We Provide Useful Services</h2>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 col-md-6" v-for="(list,index) in items" :key="index">
          <CardStyle1>
            <template #cardMedia>
              <div>
              <img :src="list.src" alt="fancy-list">
            </div>
            </template>
            <template #cardTitle>
              <div>
              <h4 class="mb-2">{{ list.title }}</h4>
            </div>
            </template>
            <template #cardBody>
              <div>
              <p>{{ list.description }}</p>
            </div>
            </template>
            <template #cardList>
              <div class="text-left">
              <ul class="iq-list">
                <li> <i class="fas fa-check-square"></i><span>Advance Advisory Team</span> </li>
                <li> <i class="fas fa-check-square"></i><span>Professional Consulting Services</span> </li>
                <li> <i class="fas fa-check-square"></i><span>Advance Advisory Team</span> </li>
              </ul>
            </div>
            </template>
          </CardStyle1>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
import CardStyle1 from '../themes/Card/CardStyle1' 
export default {
  name: 'Services',
  components: { CardStyle1 },
  data() {
    return{
      items : [
        {
          title: 'Data Analytics',
          description: 'It is a long established fact that a reader will be distracted by the of readable content.',
          src: '/assets/images/services/01.png'
        },
        {
          title: 'Managed Analytics',
          description: 'It is a long established fact that a reader will be distracted by the of readable content.',
          src: '/assets/images/services/02.png'
        },
        {
          title: 'Big Data Services',
          description: 'It is a long established fact that a reader will be distracted by the of readable content.',
          src: '/assets/images/services/03.png'
        },
        {
          title: 'Data Science',
          description: 'It is a long established fact that a reader will be distracted by the of readable content.',
          src: '/assets/images/services/04.png'
        },
        {
          title: 'Business Intelligence',
          description: 'It is a long established fact that a reader will be distracted by the of readable content.',
          src: '/assets/images/services/05.png'
        },
        {
          title: 'Data Visualization',
          description: 'It is a long established fact that a reader will be distracted by the of readable content.',
          src: '/assets/images/services/06.png'
        }
      ]
    }
  }
}
</script>

// src/react/components/home-section/landing-page2/services/index.js
import React from 'react';

import { CardStyle2, SectionTitle, CheckboxList} from '../../../xamin';

class Index extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            list: [
                {
                    media: require('../../../../public/assets/images/services/01.png'),
                    title: 'Data Analytics',
                    description: 'It is a long established fact that a reader will be distracted by the of readable content .'
                },
                {
                    media: require('../../../../public/assets/images/services/02.png'),
                    title: 'Managed Analytics',
                    description: 'It is a long established fact that a reader will be distracted by the of readable content .'
                },
                {
                    media: require('../../../../public/assets/images/services/03.png'),
                    title: 'Big Data Services',
                    description: 'It is a long established fact that a reader will be distracted by the of readable content .'
                },
                {
                    media: require('../../../../public/assets/images/services/04.png'),
                    title: 'Data Science',
                    description: 'It is a long established fact that a reader will be distracted by the of readable content .'
                },
                {
                    media: require('../../../../public/assets/images/services/05.png'),
                    title: 'Business Intelligence',
                    description: 'It is a long established fact that a reader will be distracted by the of readable content .'
                },
                {
                    media: require('../../../../public/assets/images/services/06.png'),
                    title: 'Data Visualization',
                    description: 'It is a long established fact that a reader will be distracted by the of readable content .'
                }
            ],
            checkList:[
                'Advance Advisory Team',
                'Professional Consulting Services',
                'Advance Advisory Team',
            ]
        }
    }

    render() {
        const { list,checkList } = this.state;
        return (
            <>
               <section className="aboutus-two-service">
                    <div className="container">
                        <div className="row">
                            <div className="col-lg-12">
                                <SectionTitle 
                                    link="our Services"
                                    title="We Provide Useful Services"
                                    className ="title-box wow fadeInUp text-center"
                                    spanclass="title-design"
                                />
                            </div>
                        </div>
                        <div className="row">
                            { list.map((item, index) => (
                                <div key={index} className="col-lg-4 col-md-6">
                                    <CardStyle2 media={item.media} >
                                            <h4 className="mb-2">{item.title}</h4>
                                            <p> {item.description} </p>
                                            <CheckboxList text={"text-left"} items={checkList} />
                                    </CardStyle2>
                                </div>
                              )) }
                        </div>
                    </div>
               </section>
            </>
        );
    }
}

export default Index;
