// src/react/components/service-section/services/services/index.js
import React from 'react';
import { CardStyle6, CheckboxList } from '../../../xamin';

class Index extends React.Component {
    constructor(props) {
        super(props);
        this.state={
            cards:[
                {
                    image: require("../../../../public/assets/images/services/01.png"),
                    title:'Big Data Consulting',
                    description:'All your big data through robust solutions that empower data collection, storage, processing and analysis.',
                    checklist:[
                        'Advance Advisory Team',
                        'Professional Consulting Services',
                        'Advance Advisory Team'
                    ]
                },
                {
                    image: require("../../../../public/assets/images/services/02.png"),
                    title:'Big Data Consulting',
                    description:'All your big data through robust solutions that empower data collection, storage, processing and analysis.',
                    checklist:[
                        'Advance Advisory Team',
                        'Professional Consulting Services',
                        'Advance Advisory Team'
                    ]
                },
                {
                    image: require("../../../../public/assets/images/services/03.png"),
                    title:'Big Data Consulting',
                    description:'All your big data through robust solutions that empower data collection, storage, processing and analysis.',
                    checklist:[
                        'Advance Advisory Team',
                        'Professional Consulting Services',
                        'Advance Advisory Team'
                    ]
                },
                {
                    image: require("../../../../public/assets/images/services/01.png"),
                    title:'Big Data Consulting',
                    description:'All your big data through robust solutions that empower data collection, storage, processing and analysis.',
                    checklist:[
                        'Advance Advisory Team',
                        'Professional Consulting Services',
                        'Advance Advisory Team'
                    ]
                },
                {
                    image: require("../../../../public/assets/images/services/02.png"),
                    title:'Big Data Consulting',
                    description:'All your big data through robust solutions that empower data collection, storage, processing and analysis.',
                    checklist:[
                        'Advance Advisory Team',
                        'Professional Consulting Services',
                        'Advance Advisory Team'
                    ]
                },
                {
                    image: require("../../../../public/assets/images/services/03.png"),
                    title:'Big Data Consulting',
                    description:'All your big data through robust solutions that empower data collection, storage, processing and analysis.',
                    checklist:[
                        'Advance Advisory Team',
                        'Professional Consulting Services',
                        'Advance Advisory Team'
                    ]
                },
            ]
        }
    }
    render() {
        let { cards } = this.state;
        return (
            <>
               <section className="pb-0">
                   <div className="container">
                       <div className="row">
                           {
                               cards.map((item,index) => (
                                   <div className={"col-lg-4 col-md-6"}>
                                       <CardStyle6
                                           image={item.image}
                                           title={item.title}
                                           description={item.description}
                                       >
                                            <div className="text-left">
                                                <CheckboxList items={item.checklist} />
                                            </div>
                                       </CardStyle6>
                                   </div>
                               ))
                           }
                       </div>
                   </div>
               </section>
            </>
        );
    }
}

export default Index;

// src/vue/components/Services/Services.vue
<template>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-md-6" v-for="(list,index) in items" :key="index">
          <CardStyle1>
            <template #cardMedia>
              <div>
              <img :src="list.src" alt="fancy-list">
            </div>
            </template>
            <template #cardTitle>
              <div>
                <h4 class="mb-2">{{ list.title }}</h4>
              </div>
            </template>
           <template #cardBody>
             <div >
               <p>{{ list.description }}</p>
             </div>
           </template> 
           <template #cardList>
             <div class="text-left">
               <ul class="iq-list">
                 <li> <i class="fas fa-check-square"></i><span>Advance Advisory Team</span> </li>
                 <li> <i class="fas fa-check-square"></i><span>Professional Consulting Services</span> </li>
                 <li> <i class="fas fa-check-square"></i><span>Advance Advisory Team</span> </li>
               </ul>
             </div>
           </template>
          </CardStyle1>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
import CardStyle1 from '../themes/Card/CardStyle1' 
export default {
  name: 'Services',
  components: { CardStyle1 },
  data() {
    return{
      items : [
        {
          title: 'Big Data Consulting',
          description: 'All your big data through robust solutions that empower data collection, storage, processing and analysis',
          src: '/assets/images/services/01.png'
        },
        {
          title: 'Machine Learning',
          description: 'All your big data through robust solutions that empower data collection, storage, processing and analysis',
          src: '/assets/images/services/02.png'
        },
        {
          title: 'Computer Vision',
          description: 'All your big data through robust solutions that empower data collection, storage, processing and analysis',
          src: '/assets/images/services/03.png'
        },
        {
          title: 'Data Analytics',
          description: 'All your big data through robust solutions that empower data collection, storage, processing and analysis',
          src: '/assets/images/services/01.png'
        },
        {
          title: 'Internet Of Things',
          description: 'All your big data through robust solutions that empower data collection, storage, processing and analysis',
          src: '/assets/images/services/02.png'
        },
        {
          title: 'Artificial Intelligence',
          description: 'All your big data through robust solutions that empower data collection, storage, processing and analysis',
          src: '/assets/images/services/03.png'
        }
      ]
    }
  }
}
</script>
