// src/vue/components/LandingPage3/AboutUs.vue
<template>
   <section class="pt-0">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-lg-6 mb-3 mb-lg-0 wow fadeInUp text-center">
            <img alt="" class="single_image-img attachment-full" width="666" height="400"  src="/assets/images/about-us/10.png" />
          </div>
          <div class="fadeInUp col-sm-12 col-lg-6 wow align-items-center">
            <div class="title-box wow fadeInUp text-left">
              <span class="title-design">About us</span>
              <h2>Focused on Actionable Insights</h2>
              <p>It is a long established fact that a reader will be distracted by the<br>
                  readable content of a page when looking at its layout.It is a long established fact that a reader will be distractedMany desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for</p>
            </div>
            <div class="text-left">
              <a class="button button-icon" href="#">
                <span class="btn-effect"> Read More</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
</template>
<script>
export default {
    name:'AboutUs'
}
</script>

// src/react/components/home-section/landing-page3/about-us/index.js
import React from 'react';

import { SectionLeftImage } from '../../../xamin';
import Link from 'next/link';

import img from "../../../../public/assets/images/about-us/07.png"
class Index extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <>
               <SectionLeftImage
                   sectionClass="pt-0"
                   image={img}
                   title="About us"
                   subTitle="Focused on Actionable Insights"
                   description="It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.It is a long established fact that a reader will be distractedMany desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for"
               >
                   <div className="text-left">
                       <Link className="button button-icon" href="#">
                           <span className="btn-effect"> Read More</span>
                       </Link>
                   </div>
               </SectionLeftImage>
            </>
        );
    }
}

export default Index;
