// src/vue/components/LandingPage7/AboutUs.vue
<template>
  <section class="position-relative">
    <img src="/assets/images/about-us/06.png" class="about-box-img " alt="">
    <div class="container">
      <div class="row">
        <div class="col-lg-6"> </div>
        <div class="col-lg-6 wow fadeInUp align-items-center">
          <div class="title-box wow fadeInUp text-left">
            <span class="title-design">About us</span>
            <h2>What is Sentiment Analysis?</h2>
            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
            <p>Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.</p>
          </div>
          <div class="text-left">
            <ul class="iq-list">
              <li> <i class="fas fa-check-square"></i> <span>Polarity: if the speaker express a positive or negative opinion,</span> </li>
              <li> <i class="fas fa-check-square"></i> <span>Subject: the thing that is being talked about</span> </li>
              <li> <i class="fas fa-check-square"></i> <span> Opinion holder: the person, or entity that expresses the opinion.</span> </li>
            </ul>
          </div>
          <div class=" text-left mt-5 ">
            <a class="button button-icon" href="#"> <span class="btn-effect"> View Details</span> </a>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {
  name: 'AboutUs'
}
</script>

// src/react/components/home-section/landing-page3/about-us/index.js
import React from 'react';

import { SectionLeftImage } from '../../../xamin';
import Link from 'next/link';

import img from "../../../../public/assets/images/about-us/07.png"
class Index extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <>
               <SectionLeftImage
                   sectionClass="pt-0"
                   image={img}
                   title="About us"
                   subTitle="Focused on Actionable Insights"
                   description="It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.It is a long established fact that a reader will be distractedMany desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for"
               >
                   <div className="text-left">
                       <Link className="button button-icon" href="#">
                           <span className="btn-effect"> Read More</span>
                       </Link>
                   </div>
               </SectionLeftImage>
            </>
        );
    }
}

export default Index;
