// src/react/components/home-section/landing-page8/services/index.js
import React from 'react';

import { SectionTitle,CardStyle15 } from '../../../xamin';


class Index extends React.Component {

    constructor(props) {
        super(props);

        this.state = {
            cardData: [
                {
                    images:  require("../../../../public/assets/images/services/02.png"),
                    name: "Big Data Consulting",
                    description: "Many variation established fact reader will be distracted by the of readable content . ",
                },
                {
                    images:  require("../../../../public/assets/images/services/03.png"),
                    name: "Machine Learning",
                    description: "Many variation established fact reader will be distracted by the of readable content . ",
                },
                {
                    images:  require("../../../../public/assets/images/services/04.png"),
                    name: "Computer Vision",
                    description: "Many variation established fact reader will be distracted by the of readable content . ",
                },
                {
                    images:  require("../../../../public/assets/images/services/04.png"),
                    name: "Data Analytics",
                    description: "Established fact that a reader will be distracted by passages the of readable content . ",
                },
                {
                    images:  require("../../../../public/assets/images/services/02.png"),
                    name: "Internet Of Things",
                    description: "It is a long established fact that a reader will be distracted by the of readable content . ",
                },
                {
                    images:  require("../../../../public/assets/images/services/04.png"),
                    name: " Artificial Intelligence",
                    description: "Contrary to established fact that a reader will be distracted by the of readable content . ",
                },
               
            ]
        }

    }

    render() {
        let { cardData } = this.state;
        return (
            <>
              <section className="pt-0">
                  <div className="container">

                
                <div className="row">
                     <div className="col-sm-12 wow fadeInUp">
                        <SectionTitle
                                link="OUR SERVICES"
                                className = "title-box wow fadeInUp text-center"
                                title="Chosen Usage Examples"
                                spanclass="title-design"
                        />
                    </div>
                </div>
                <div className="row">
                   
                            {
                                cardData.map((card, index) => (
                                    <CardStyle15
                                        key={index}
                                        images={card.images}
                                        name={card.name}
                                        description={card.description}
                                        className= {"servicebox-userbehavior wow fadeInUp  text-left"}
                                    />
                                ))
                            }
               </div>
               </div>
               </section>
            </>
        );
    }

}

export default Index;

// src/vue/components/LandingPage8/Services.vue
<template>
  <section class="pt-0 iq-pb-30">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="title-box wow fadeInUp text-center">
            <span class="title-design">our Services</span>
            <h2>We Provide Useful Services</h2>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 col-md-6 ">
          <div class="servicebox-userbehavior wow fadeInUp  text-left">
            <div class="service-box-icon">
              <img src="/assets/images/services/02.png" alt="fancybox">
            </div>
            <div class="service-box-detail">
              <h4 class="mb-2">Big Data Consulting</h4>
              <p>Many variation established fact reader will be distracted by the of readable content .</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 ">
          <div class="servicebox-userbehavior wow fadeInUp  text-left">
            <div class="service-box-icon">
              <img src="/assets/images/services/03.png" alt="fancybox">
            </div>
            <div class="service-box-detail">
              <h4 class="mb-2"> Machine Learning</h4>
              <p>Contrary to established fact that a reader will be distracted by the of readable content .</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 ">
          <div class="servicebox-userbehavior wow fadeInUp  text-left">
            <div class="service-box-icon">
              <img src="/assets/images/services/04.png" alt="fancybox">
            </div>
            <div class="service-box-detail">
              <h4 class="mb-2">Computer Vision</h4>
              <p>Variations established fact that a reader will be distracted the of readable content .</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6  ">
          <div class="servicebox-userbehavior wow fadeInUp  text-left ">
            <div class="service-box-icon">
              <img src="/assets/images/services/04.png" alt="fancybox">
            </div>
            <div class="service-box-detail">
              <h4 class="mb-2">Data Analytics</h4>
              <p>Established fact that a reader will be distracted by passages the of readable content .</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6  pb-0">
          <div class="servicebox-userbehavior wow fadeInUp  text-left mb-md-0">
            <div class="service-box-icon">
              <img src="/assets/images/services/02.png" alt="fancybox">
            </div>
            <div class="service-box-detail">
              <h4 class="mb-2">Internet Of Things</h4>
              <p>It is a long established fact that a reader will be distracted by the of readable content .</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6  pb-0">
          <div class="servicebox-userbehavior wow fadeInUp  text-left mb-0">
            <div class="service-box-icon">
              <img src="/assets/images/services/03.png" alt="fancybox">
            </div>
            <div class="service-box-detail">
              <h4 class="mb-2">   Artificial Intelligence</h4>
              <p>Contrary to established fact that a reader will be distracted by the of readable content .</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {

}
</script>
