// src/react/components/home-section/landing-page5/feature/index.js
import React from 'react';

import { SectionTitle,PartnerCardStyle } from '../../../xamin';




class Index extends React.Component {

    constructor(props) {
        super(props);

        this.state = {
            cardData: [
                {
                    img: require('../../../../public/assets/images/services/01.png'),
                    heading:"Embeded",
                    text:"It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout."
                   
                },
                {
                    img: require('../../../../public/assets/images/services/02.png'),
                    heading:"Embeded",
                    text:"It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout."
                    
                },
                {
                    img: require('../../../../public/assets/images/services/03.png'),
                    heading:"Embeded",
                    text:"It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout."
                },
               
              
            ],
            cardData1: [
                {
                    img: require('../../../../public/assets/images/services/04.png'),
                    heading:"MashUp",
                    text:"It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout."
                   
                },
                {
                    img: require('../../../../public/assets/images/services/05.png'),
                    heading:"Impact",
                    text:"It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout."
                    
                },
                {
                    img: require('../../../../public/assets/images/services/06.png'),
                    heading:"Control",
                    text:"It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout."
                },
               
              
            ],
           
        }

    }

    render() {
        const list =this.state.cardData;
      
        return (
            <>  
                <section className="iq-bg-over">
                    <div className="container">
                        <div className="row">
                            <div className="col-md-12">
                                <SectionTitle
                                    className={"title-box wow fadeInUp text-center"}
                                    spanclass={"title-design"}
                                    link={"FEATURES"}
                                    title={"Everything You Need  to Build Powerful Analytic Apps"}
                                />
                            </div>

                        </div>

                        <div className="row">
                            <div className="col-md-6">
                                { list.map((item, index) => (
                                    <PartnerCardStyle 
                                    key={index}
                                        img ={item.img}
                                        heading ={item.heading}
                                        text ={item.text}
                                        mainClass="xamin-analytics text-left"
                                        imgClass="analytics-icon"
                                        detailClass="analytics-detail"
                                        key={index}
                                      
                                    />
                            )) }
                            </div>

                            <div className="col-md-6">
                                { this.state.cardData1.map((item, index) => (
                                    <PartnerCardStyle 
                                    key={index+1}
                                        img ={item.img}
                                        heading ={item.heading}
                                        text ={item.text}
                                        mainClass="xamin-analytics text-left"
                                        imgClass="analytics-icon"
                                        detailClass="analytics-detail"
                                        key={'list-'+index}
                                    />
                            )) }
                            </div>

                        </div>

                    </div>

                </section>
            </>
        );
    }

}

export default Index;

// src/vue/components/LandingPage19/Feature.vue
<template>
  <section class="position-relative overview-block-pt xamin-custom-bg iq-pb-55">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 wow fadeInUp">
          <div class="title-box wow fadeInUp text-center">
            <span class="title-design">FEATURES</span>
            <h2>We will hope you learn what about</h2>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-6 align-self-center">
          <img src="/assets/images/others/13.png" class="img-fluid" alt="">
        </div>
        <div class="col-lg-6 mt-3 mt-lg-0 wow fadeInUp align-items-center">
          <div class="service-box wow fadeInUp  text-left">
            <i aria-hidden="true" class="ion ion-disc" />
            <div class="service-detail align-self-center">
              <h4 class="mb-2">
                Discover
              </h4><p>It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout.</p>
            </div>
          </div>
          <div class="service-box wow fadeInUp  text-left">
            <i aria-hidden="true" class="ion ion-nuclear" />
            <div class="service-detail align-self-center">
              <h4 class="mb-2">
                Learn
              </h4><p>It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout.</p>
            </div>
          </div>
          <div class="service-box wow fadeInUp  text-left">
            <i aria-hidden="true" class="ion ion-android-expand" />
            <div class="service-detail align-self-center">
              <h4 class="mb-2">
                Experience
              </h4><p>It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {
  name: 'Feature'
}
</script>
