// src/react/components/service-section/artificial-intelligence/footer/index.js
import React from 'react';

import { FooterMain, FooterLogo, FooterAddress, FooterLinks } from '../../../xamin';
import Link from 'next/link';

import img from '../../../../public/assets/images/logo.png'
class Index extends React.Component {

    constructor(props) {
        super(props);

        this.state = {
            footerText: [
                {
                    icon: true,
                    iconClass: 'fa fa-phone',
                    text: '+0123456789'
                },
                {
                    icon: true,
                    iconClass: 'fa fa-envelope',
                    text: 'support@iqnonicthemes.com'
                },
                {
                    icon: true,
                    iconClass: 'fa fa-home',
                    text: '1234 North Avenue Luke Lane, South Bend, IN 360001'
                }
            ],
            footerHome: [
                {
                    section: [
                        {
                            href: '#',
                            title: 'Home'
                        },
                        {
                            href: '#',
                            title: 'Blog'
                        },
                        {
                            href: '#',
                            title: 'Careers'
                        },
                        {
                            href: '#',
                            title: 'Clients'
                        }, 
                        {
                            href: '#',
                            title: 'Service'
                        }
                    ]
                },
                
            ],
            footerAbout: [
                {
                    section: [
                        {
                            href: '#',
                            title: 'Home'
                        },
                        {
                            href: '#',
                            title: 'Blog'
                        },
                        {
                            href: '#',
                            title: 'Careers'
                        },
                        {
                            href: '#',
                            title: 'Clients'
                        }, 
                        {
                            href: '#',
                            title: 'Service'
                        }
                    ]
                },
                
            ],
        }

    }

    render() {
        const { footerText, footerHome, footerAbout } = this.state;
        return (
            <>
                <FooterMain className={"footer-one iq-bg-dark iq-over-dark-90"}>
                    <div className="container">
                            <div className="footer-top">

                                 
                                <div className="row">
                                    <div className="col-lg-4 col-md-6 col-sm-6 ">
                                        <FooterLogo
                                            sectionImage={img}
                                            sectionText={"It is a long established fact that a reader will be distracted by the readable content."}
                                            
                                        />
                                    </div>
                                    <div className="col-lg-2 col-md-6 col-sm-6 mt-4 mt-lg-0 mt-md-0">
                                        <FooterLinks title={"Menu"} content={footerHome}  />
                                    </div>
                                

                                    <div className="col-lg-2 col-md-6 col-sm-6 mt-lg-0 mt-4">
                                        <FooterLinks title={"About us"} content={footerAbout}  />
                                    </div>

                                    <div className="col-lg-4 col-md-6 col-sm-6 mt-lg-0 mt-4">
                                        <FooterAddress  addressContent={footerText} addressTitle={"Contact Us"} />
                                    </div>
                                </div>
                    </div>
                    </div>
                    <footer>
                        <div className="copyright-footer">
                                <div className="pt-3 pb-3">
                                    <div className="row flex-row-reverse justify-content-between">
                                        <div className="col-lg-12 col-md-12 text-lg-center text-md-center text-center"> <span className="copyright">Copyright 2019 <Link href="index.html">Xamin</Link> All Rights Reserved.</span> </div>
                                    </div>
                                </div>
                            </div>
                    </footer>
                </FooterMain>
               
            </>
        );
    }

}

export default Index;

// src/vue/components/LandingPage13/Footer.vue
<template>
  <FooterMain class="footer-one iq-bg-dark iq-over-dark-90">
    <template #footerContent>
      <div class="footer-top">
      <div class="row">
        <div class="col-lg-4 col-md-6 col-sm-6">
          <FooterLogo
            :section-image="navLogo"
            section-text="It is a long established fact that a reader will be distracted by the readable content."
          />
        </div>
        <div class="col-lg-2 col-md-6 col-sm-6 mt-4 mt-lg-0 mt-md-0">
          <FooterLinks :content="footerHome" title="Menu" />
        </div>
        <div class="col-lg-2 col-md-6 col-sm-6 mt-4 mt-lg-0 mt-md-0">
          <FooterLinks :content="footerHome" title="About Us" />
        </div>
        <div class="col-lg-4 col-md-6 col-sm-6 mt-lg-0 mt-4">
          <FooterAddress :address-content="footerText" address-title="Contact us" class="iq-contact" />
        </div>
      </div>
    </div>
    </template>
  </FooterMain>
</template>
<script>
import FooterMain from '../themes/Partials/Footer/FooterMain'
import FooterLogo from '../themes/Partials/FooterComponents/FooterLogo'
import FooterAddress from '../themes/Partials/FooterComponents/FooterAddress'
import FooterLinks from '../themes/Partials/FooterComponents/FooterLinks'
import logoImg from '/assets/images/logo.png'

export default {
  name: 'Footer',
  components: { FooterLogo, FooterLinks, FooterAddress, FooterMain },
  data () {
    return {
      navLogo: logoImg,
      footerText: [
        {
          icon: true,
          iconClass: 'fa fa-phone',
          text: '+0123 456 789'
        },
        {
          icon: true,
          iconClass: 'fas fa-envelope',
          text: 'support@iqnonicthemes.com'
        },
        {
          icon: true,
          iconClass: 'fas fa-home',
          text: '1234 North Luke Lane, South Bend, IN 360001'
        }
      ],
      footerHome: [
        {
          href: 'javascript:void(0)',
          title: 'Home'
        },
        {
          href: 'javascript:void(0)',
          title: 'Blog'
        },
        {
          href: 'javascript:void(0)',
          title: 'Careers'
        },
        {
          href: 'javascript:void(0)',
          title: 'Clients'
        },
        {
          href: 'javascript:void(0)',
          title: 'Service'
        }
      ]
    }
  }
}
</script>

<style scoped></style>
