// src/react/components/home-section/landing-page2/video/index.js
import React from 'react';

import { WaveBox} from '../../../xamin';
import Image from 'next/image';

import img from "../../../../public/assets/images/about-us/09.jpg"

class Index extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        

        return (
            <>
               <div className="iq-ptb-100">
                    <div className="container">
                        <div className="row xamin-bg">
                            <div className="col-sm-12 offset-md-1 offset-lg-1 col-md-10 col-lg-10 wow fadeInUp text-center">
                                <div>
                                    <div className="scroll-effect">
                                        <Image src={img} className="img-fluid img-one" alt="#" />
                                        <div className="main-video">
                                            <div className="video-img">
                                                <WaveBox />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </>
        );
    }
}

export default Index;

// src/vue/components/LandingPage2/Video.vue
<template>
	<div class="iq-ptb-100">
		<div class="container">
			<div class="row xamin-bg">
				<div class="col-sm-12 offset-md-1 offset-lg-1 col-md-10 col-lg-10 wow fadeInUp text-center">
					<div>
						<div class="scroll-effect">
							<img src="/assets/images/about-us/09.jpg" class="img-fluid img-one" alt="#" />
							<div class="main-video">
								<div class="video-img">
									<div class="consult-video video-btn">
										<div class="btn-waves">
											<div class="waves wave-1"></div>
											<div class="waves wave-2"></div>
											<div class="waves wave-3"></div>
										</div>
										<a href="http://www.youtube.com/watch?v=0O2aH4XLbto" class="iq-video popup-youtube"><i class="fa fa-play"></i></a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>
<script>
export default {
	name: 'Video'
}
</script>
