// src/react/components/home-section/landing-page11/blog/index.js
import React from 'react';
import Link from "next/link";
import Image from 'next/image'
import { SectionTitle,SectionStyle3 } from '../../../xamin';

const Blog = (props) => {
    const bloglist = props.bloglist;
    return bloglist.map((blog, index) => (
                <div  key={index} className="item">
                    <div className="iq-blog-box mb-0">
                            <div className="iq-blog-image clearfix">
                                <Image alt="#" className="img-fluid center-block"  src={blog.img} />
                                <ul className="iq-blogtag">
                                    <li>
                                        <Link href="#">{blog.linkname}</Link>
                                    </li>
                                </ul>
                            </div>
                            <div className="iq-blog-detail">
                                <div className="iq-blog-meta">
                                    <ul>
                                        <li className="list-inline-item">
                                            <Link href='#'>
                                                <time className="entry-date published updated" >{blog.time}</time>
                                            </Link>
                                        </li>
                                    </ul>
                                </div>
                                <div className ="blog-title">
                                        <Link href="#">
                                            <h4>
                                                {blog.title}
                                            </h4>
                                        </Link>
                                </div>
                                <p>
                                    {blog.desc}
                                </p>
                                <div className="blog-button">
                                    <Link href="/blog-details">
                                        <span className="button-link" >Read More<i className="fa fa-angle-right" aria-hidden="true"></i></span>
                                    </Link>
                                </div>
                            </div>
                        </div>
                </div>
    ));
};

class Index extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            cardData: [
                {
                    img: require("../../../../public/assets/images/about-us/04.png"),
                    linkname:  "HTML",
                    time: "September 26, 2019 ",
                    title: "Build Construction",
                    desc: "“They bring to you a host of beautifully created infographics that contain the latest digital marketing ",
                },
                {
                    img: require("../../../../public/assets/images/about-us/04.png"),
                    linkname:  "Design",
                    time: "September 26, 2019 ",
                    title: "Life Lack Meaning",
                    desc: "They bring to you a host of beautifully created infographics that contain the latest digital marketing.",
                },
                {
                    img: require("../../../../public/assets/images/about-us/04.png"),
                    linkname:  "HTML",
                    time: "September 26, 2019 ",
                    title: "Construction industry",
                    desc: "They bring to you a host of beautifully created infographics that contain the latest digital marketing",
                },
                {
                    img: require("../../../../public/assets/images/about-us/04.png"),
                    linkname:  "CSS",
                    time: "September 26, 2019 ",
                    title: "Content Marketing",
                    desc: "They bring to you a host of beautifully created infographics that contain the latest digital marketing.",
                },
               
            ]
        }
    }

    render() {

        return (
            <>
                <section className="pt-0" id="blog">
                    <div className="container">
                        <div className="row layer-fly-one">
                            <div className="col-md-12">
                                <SectionTitle
                                        link="BLOG"
                                        className = "title-box wow fadeInUp title-shadow  text-center"
                                        title="Recent Blog"
                                        spanclass="title-design"
                                />
                                <div className="xamin-recentblog v1">
                                    <div className="owl-carousel owl-loaded owl-drag" data-dots="false" data-nav="false" data-items="3" data-items-laptop="3" data-items-tab="2" data-items-mobile="1" data-items-mobile-sm="1" data-autoplay="true" data-loop="true">
                                         <Blog bloglist={this.state.cardData} />
                                    </div>
                                </div>
                            </div>
                        </div>
                        
               </div>
                </section>
            </>
        );
    }

}

export default Index;

// src/vue/components/LandingPage12/Blog.vue
<template>
  <section class="pt-0">
    <div class="container">
      <div class="row layer-fly-one ">
        <div class="col-md-12">
          <div class="title-box wow fadeInUp title-shadow  text-center">
            <span class="title-design">Blog</span>
            <h2>Recent Blog</h2>
          </div>
          <div class="xamin-recentblog v1">
            <div
              class="owl-carousel owl-loaded owl-drag"
              data-dots="false"
              data-nav="false"
              data-items="3"
              data-items-laptop="3"
              data-items-tab="2"
              data-items-mobile="1"
              data-items-mobile-sm="1"
              data-autoplay="true"
              data-loop="true"
            >
              <div v-for="(item,index) in items" :key="index" class="item">
                <div class="iq-blog-box mb-0">
                  <div class="iq-blog-image clearfix">
                    <img :src="item.src" class="img-fluid center-block" alt="blogimage">
                    <ul class="iq-blogtag">
                      <li><a href="#">{{ item.tag }}</a> </li>
                    </ul>
                  </div>
                  <div class="iq-blog-detail">
                    <div class="iq-blog-meta">
                      <ul>
                        <li class="list-inline-item">
                          <span class="screen-reader-text">Posted on</span> <a href="#" rel="bookmark"> <time class="entry-date published updated" datetime="2019-09-26T06:51:19+00:00">{{ item.date }} </time> </a>
                        </li>
                      </ul>
                    </div>
                    <div class="blog-title">
                      <a href="#">
                        <h4>{{ item.title }}</h4>
                      </a>
                    </div>
                    <p>{{ item.description }}</p>
                    <div class="blog-button">
                      <a class="button-link" href="#">Read More<i class="fa fa-angle-right" aria-hidden="true" /></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: 'Blog',
  data () {
    return {
      items: [
        {
          title: 'Build Construction',
          tag: 'HTML',
          date: 'September 26, 2019',
          description: 'They bring to you a host of beautifully created infographics that contain the latest digital marketing.',
          src: '/assets/images/about-us/02.png'
        },
        {
          title: 'Life Lack Meaning',
          tag: 'Design',
          date: 'September 26, 2019',
          description: 'They bring to you a host of beautifully created infographics that contain the latest digital marketing.',
          src: '/assets/images/about-us/04.png'
        },
        {
          title: 'Construction industry',
          tag: 'HTML',
          date: 'September 26, 2019',
          description: 'They bring to you a host of beautifully created infographics that contain the latest digital marketing.',
          src: '/assets/images/about-us/03.png'
        },
        {
          title: 'Content Marketing',
          tag: 'CSS',
          date: 'September 26, 2019',
          description: 'They bring to you a host of beautifully created infographics that contain the latest digital marketing.',
          src: '/assets/images/about-us/02.png'
        }
      ]
    }
  }
}
</script>
