// src/react/components/home-section/landing-page3/partner/index.js
import React from 'react';

import { Carousel } from '../../../xamin';

class Index extends React.Component {

    constructor(props) {
        super(props);

        this.state = {
            cardData1: [
                {
                    img:  require('../../../../public/assets/images/partners/1.png'),
                   
                },
                {
                    img:  require('../../../../public/assets/images/partners/2.png'),
                    
                },
                {
                    img:  require('../../../../public/assets/images/partners/3.png'),
                    
                },
                {
                    img:  require('../../../../public/assets/images/partners/4.png'),
                    
                },
                {
                    img:  require('../../../../public/assets/images/partners/5.png'),
                    
                }
            ],
           
        }

    }

    render() {

        return (
            <>
                <div className="iq-pb-100">
                    <div className="container">
                        <div className="row">
                            <div className="col-md-12">
                                <div className="owl-carousel owl-loaded owl-drag"
                                    data-dots="false"
                                    data-nav="false"
                                    data-items="6"
                                    data-items-laptop="4"
                                    data-items-tab="3"
                                    data-items-mobile="2"
                                    data-items-mobile-sm="1"
                                    data-autoplay="true"
                                    data-loop="true"
                                    data-margin="30"
                                >
                                        { this.state.cardData1.map((item, index) => (
                                                <Carousel
                                                    key={index}
                                                    img ={item.img}
                                                    imgClass ="img-fluid client-img"
                                                />
                                        )) }
                                </div>
                            </div>
                        </div>
                        
               </div>
                </div>
            </>
        );
    }

}

export default Index;

// src/vue/components/LandingPage12/Partner.vue
<template>
  <div class="position-relative border-bottom iq-banking-client">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div
            class="owl-carousel owl-loaded owl-drag"
            data-dots="false"
            data-nav="false"
            data-items="6"
            data-items-laptop="4"
            data-items-tab="3"
            data-items-mobile="2"
            data-items-mobile-sm="1"
            data-dots-mobile="true"
            data-autoplay="true"
            data-loop="true"
            data-margin="30"
          >
            <div v-for="(item,index) in list" :key="index" class="item">
              <div class="clients-box">
                <img class="img-fluid client-img" :src="item.image" alt="image0">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  name: 'Partner',
  data () {
    return {
      list: [
        {
          image: '/assets/images/partners/1.png'
        },
        {
          image: '/assets/images/partners/2.png'
        },
        {
          image: '/assets/images/partners/3.png'
        },
        {
          image: '/assets/images/partners/4.png'
        },
        {
          image: '/assets/images/partners/5.png'
        },
        {
          image: '/assets/images/partners/1.png'
        }
      ]
    }
  }
}
</script>
