// src/react/components/home-section/landing-page9/education/index.js
import React from 'react';

import {  SectionTitle, AdressSection} from '../../../xamin';
import Link from 'next/link';
import Image from 'next/image';

class   Index extends React.Component {
    constructor(props) {
        super(props);
        this.state={
            data:[
                {
                    heading:"B.S Computer Science",
                    text:"University of Altoona",
                    span:"2007-2010",
                    subtitle:"GPA",
                    point:"4.50/5.00",
                    img: require("../../../../public/assets/images/fancybox/9-1.png")
                },
                {
                    heading:"M.S Computer Application",
                    text:"University of Data Science Altoona",
                    span:"2006-2007",
                    subtitle:"GPA",
                    point:"3.50/4.0",
                    img: require("../../../../public/assets/images/fancybox/9-1.png")
                },
                {
                    heading:"BSc in Mathematics and Statistics",
                    text:"University of Data Science Altoona",
                    span:"2006-2007",
                    subtitle:"GPA",
                    point:"3.50/4.0",
                    img: require("../../../../public/assets/images/fancybox/9-1.png")
                },
                {
                    heading:"B.S Computer Science",
                    text:"University of Altoona",
                    span:"2006-2007",
                    subtitle:"GPA",
                    point:"4.50/4.0",
                    img: require("../../../../public/assets/images/fancybox/9-1.png")
                },
                {
                    heading:"M.S Computer Application",
                    text:"University of Data Science Altoona",
                    span:"2006-2007",
                    subtitle:"GPA",
                    point:"3.50/4.0",
                    img: require("../../../../public/assets/images/fancybox/9-1.png")
                },
                {
                    heading:"BSc in Mathematics and Statistics",
                    text:"University of Data Altoona",
                    span:"2006-2007",
                    subtitle:"GPA",
                    point:"3.50/4.0",
                    img: require("../../../../public/assets/images/fancybox/9-1.png")
                },
                {
                    heading:"B.S Computer Science",
                    text:"University of Altoona",
                    span:"2006-2007",
                    subtitle:"GPA",
                    point:"4.50/4.0",
                    img: require("../../../../public/assets/images/fancybox/9-1.png")
                },
            ]
        }
    }

    render() {
        const list=this.state.data;
        return (
            <>
                <section className="pt-0">
                    <div className="container">
                        <div className="row">
                            <div className="col-md-12">
                                <SectionTitle
                                    className={"title-box wow fadeInUp text-center"}
                                    spanclass={"title-design"}
                                    title={"Education"}
                                   
                                />
                            </div>

                        </div>

                        <div className="row">
                            <div className="col-md-12">
                                <div className="data-science">
                                    <div className="owl-carousel testimonial-style owl-loaded owl-drag" data-dots="false" data-nav="false" data-autoplay="false" data-loop="true" data-items="2" data-items-laptop="2" data-items-tab="1" data-items-mobile="1" data-items-mobile-sm="1" >
                                    { list.map((item, index) => (
                                    <div key={index} className="item">
                                        <div className="iq-boxslider-detail">
                                            <div className="boxslider-content">
                                             <div className="box-detail">
                                                    <Image className="arrow-img" src={item.img} />
                                                    <h5 className="title">{item.heading}</h5>
                                                    <p>{this.props.text}</p>
                                                    <span className="fa fa-calendar"></span><Link href="#">{item.span}</Link>
                                            </div>
                                            </div>
                                            <div className="box-gpa">
                                                <h6>{item.subtitle}</h6>
                                                <span>{item.point}</span>
                                            </div>
                                        </div>
                                    </div>
                                )) }

                                    </div>

                                </div>

                            </div>

                        </div>

                    </div>

                </section>
            </>
        );
    }
}

export default Index;

// src/vue/components/LandingPage9/Education.vue
<template>
  <section class="pt-0">
    <div class="container">
      <div class="row ">
        <div class="col-md-12">
          <div class="title-box wow fadeInUp text-center">
            <h2>Education</h2>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="data-science">
            <div class="owl-carousel testimonial-style owl-loaded owl-drag" data-dots="false" data-nav="false" data-autoplay="false" data-loop="true" data-items="2" data-items-laptop="2" data-items-tab="1" data-items-mobile="1" data-items-mobile-sm="1" >
              <div v-for="(item,index) in items" :key="index" class="item">
                <div class="iq-boxslider-detail">
                  <div class="boxslider-content">
                    <div class="box-detail">
                      <img class="arrow-img" :src="item.src" alt="fancybox">
                      <h5 class="title">{{ item.title }}</h5>
                      <p>{{ item.subtitle }}</p>
                      <span class="fas fa-calendar-alt"></span><a href="#">{{ item.year }}</a>
                    </div>
                  </div>
                  <div class="box-gpa">
                    <h6>{{ item.grade }}</h6>
                    <span>{{ item.gpa }}</span>
                  </div>
                </div>
              </div>           
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {
  name: 'Education',
  data () {
    return {
      items: [
        {
          title:'B.S Computer Science',
          subtitle:'University of Altoona',
          year: '2007-2010',
          grade: 'GPA',
          gpa: '4.50/5.00',
          src: '/assets/images/fancybox/9-1.png'
        },
        {
          title:'M.S Computer Application.',
          subtitle:'University of Data Science Altoona',
          year: '2006-2007',
          grade: 'GPA',
          gpa: '3.50/4.400',
          src: '/assets/images/fancybox/9-1.png'
        },
        {
          title:'BSc in Mathematics and Statistics',
          subtitle:'University of Data Altoona',
          year: '2006-2007',
          grade: 'GPA',
          gpa: '3.50/4.400',
          src: '/assets/images/fancybox/9-1.png'
        },
        {
          title:'B.S Computer Science',
          subtitle:'University of Altoona',
          year: '2007-2010',
          grade: 'GPA',
          gpa: '4.50/5.00',
          src: '/assets/images/fancybox/9-1.png'
        }
      ]
    }
  }
}
</script>
