// src/vue/components/AboutUs-2/About.vue
<template>
  <section class="bg-gray">
    <div class="container">
      <div class="row iq-how-it-works">
        <div class="fadeInUp   col-sm-12 col-lg-6 col-md-6 wow align-items-center">
          <div class="title-box wow fadeInUp text-left">
            <span class="title-design">About us</span>
            <h2>Human Behaviour, Data Science</h2>
            <p> It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout. </p>
          </div>
          <div class="text-left">
            <ul class="iq-list">
              <li v-for="(item,index) of list" :key="index"><i :class="item.icon"> </i><span>{{ item.title }}</span></li>
            </ul>
          </div>
        </div>
        <div class="fadeInUp col-sm-12 col-lg-6 col-md-6 wow"> <img alt="" class="single_image-img attachment-full" height="954"  src="/assets/images/about-us/03.png" width="1260" /> </div>
      </div>
      <div class="row iq-how-it-works pt-5">
        <div class="fadeInUp col-sm-12 col-lg-6 col-md-6 wow"> <img alt="" class="single_image-img attachment-full" height="954"  src="/assets/images/about-us/05.png" width="1260" /> </div>
        <div class=" fadeInUp  col-sm-12 col-lg-6 col-md-6 wow align-items-center">
          <div class="title-box wow fadeInUp text-left">
            <span class="title-design">About us</span>
            <h2>Human Behaviour, Data Science</h2>
            <p> It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout. </p>
          </div>
          <div class="text-left">
            <ul class="iq-list">
              <li v-for="(item,index) of list" :key="index"><i :class="item.icon"> </i><span>{{ item.title }}</span></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: 'About1',
  data () {
    return {
      list: [
        {
          icon: 'fas fa-check-square',
          title: 'Advance Advisory Team'
        },
        {
          icon: 'fas fa-check-square',
          title: 'Professional Consulting Services'
        },
        {
          icon: 'fas fa-check-square',
          title: '24/7 Support Help Center'
        },
        {
          icon: 'fas fa-check-square',
          title: 'Customer Service & Operations'
        }
      ]
    }
  }
}
</script>

// src/react/components/home-section/landing-page4/about/index.js
import React from 'react';

import { SectionTitle, CheckboxList} from '../../../xamin';
import Link from 'next/link';
import Image from 'next/image';

import img from "../../../../public/assets/images/about-us/13.png"
import img1 from "../../../../public/assets/images/about-us/13.png"
class   Index extends React.Component {
    constructor(props) {
        super(props);
        this.state={
            checkList:[
                'Advance Advisory Team',
                'Professional Consulting Services',
                '24/7 Support Help Center',
                'Customer Service &amp; Operations'
            ]
        }
    }

    render() {
        let { checkList } = this.state;
        return (
            <>
                <section>
                    <div className="container">
                        <div className="row">
                           <div  className="col-lg-6 wow fadeInUp align-items-center">
                                 <SectionTitle
                                    className={"title-box wow fadeInUp text-left"}
                                    spanclass={"title-design"}
                                    link={"About us"}
                                    title={"Human Behaviour, Data Science"}
                                    subTitle ={"It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout."}
                                />
                                  <CheckboxList text={"text-left"} items={checkList} />
                                  <div className=" text-left mt-5 ">
                                    <Link className="button button-icon" href="#"> <span className="btn-effect"> Read More</span> </Link>
                                 </div>
                           </div>
                            <div className="col-lg-6  wow fadeInUp ">
                                 <Image  src={img} className="attachment-full" alt="" sizes="100vw" />
                            </div>
                        </div>
                        <div className="row mt-5">
                             <div className="col-lg-6  wow fadeInUp ">
                                 <Image  src={img1} className="attachment-full" alt="" sizes="100vw" />
                            </div>
                            <div  className="col-lg-6 wow fadeInUp align-items-center">
                                 <SectionTitle
                                    className={"title-box wow fadeInUp text-left"}
                                    spanclass={"title-design"}
                                    link={"About us"}
                                    title={"Focused on Actionable Insights"}
                                    subTitle ={"It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout."}
                                />
                                  <CheckboxList text={"text-left"} items={checkList} />
                                  <div className=" text-left mt-5 ">
                                    <Link className="button button-icon" href="#"> <span className="btn-effect"> Read More</span> </Link>
                                 </div>
                           </div>
                        </div>
                    </div>
                </section>
            </>
        );
    }
}

export default Index;
