// src/react/components/about-section/about-us1/about-us/index.js
import React from 'react';

import { SectionRightImage, CheckboxList, CardStyle4 } from '../../../xamin';

import img from "../../../../public/assets/images/about-us/06.png"
class Index extends React.Component {
    constructor(props) {
        super(props);
       this.state ={
           items:[
               'Advance Advisory Team',
               'Professional Consulting Services',
               '24/7 Support Help Center',
               'Customer Service &amp; Operations'
           ],
           cards :[
               {
                   title:"Data for all people",
                   description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout."
               },
               {
                   title:"A new breed of AI",
                   description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout."
               },
               {
                   title:"Analytics business",
                   description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout."
               },
           ]
       }
    }

    render() {
        const {items,cards } = this.state;

        return (
            <>
                <SectionRightImage
                    title={"About Us"}
                    subTitle={"Human Behaviour, Data Science"}
                    description={"It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout."}
                    image={img}
                >
                    <CheckboxList
                        text={"text-left"}
                        items={items} />
                </SectionRightImage>
                <section  className="pt-0">
                    <div className="container">
                        <div className="row">
                            { cards.map((item,index) => (
                                <div key={'i1-'+index} className="col-lg-4 col-sm-12">
                                    <CardStyle4
                                        textClass="left"
                                        title={item.title}
                                        description={item.description}
                                    />
                                </div>
                            )) }
                        </div>
                    </div>
                </section>
            </>
        );
    }
}

export default Index;

// src/vue/components/LandingPage4/AboutUs.vue
<template>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-lg-6 wow fadeInUp align-items-center">
          <div class="title-box wow fadeInUp text-left">
            <span class="title-design">About us</span>
            <h2>Human Behaviour, Data Science</h2>
            <p> It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout. </p>
          </div>
          <div class="text-left">
            <ul class="iq-list">
              <li v-for="(item,index) of list" :key="index"><i :class="item.icon"> </i><span>{{ item.title }}</span></li>
            </ul>
          </div>
          <div class=" text-left mt-5 ">
            <a class="button button-icon" href="#"> <span class="btn-effect"> Read More</span> </a>
          </div>
        </div>
        <div class="col-lg-6  wow fadeInUp ">
          <img alt="" class="single_image-img attachment-full" height="954"  src="/assets/images/about-us/13.png" /> 
        </div>
       </div>
      <div class="row mt-5">
        <div class="fadeInUp col-sm-12 col-lg-6 col-md-6 wow">
          <img alt="" class="single_image-img attachment-full" src="/assets/images/about-us/13.png"/>
        </div>
        <div class="col-lg-6 wow fadeInUp align-items-center">
          <div class="title-box wow fadeInUp text-left">
            <span class="title-design">About us</span>
            <h2>Focused on Actionable Insights</h2>
            <p> It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout. </p>
          </div>
          <div class="text-left">
            <ul class="iq-list">
              <li v-for="(item,index) of list" :key="index"><i :class="item.icon"> </i><span>{{ item.title }}</span></li>
            </ul>
          </div>
          <div class=" text-left mt-5 ">
            <a class="button button-icon" href="#"> <span class="btn-effect"> Read More</span> </a>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: 'AboutUs',
  data () {
    return {
      list: [
        {
          icon: 'fas fa-check-square',
          title: 'Advance Advisory Team'
        },
        {
          icon: 'fas fa-check-square',
          title: 'Professional Consulting Services'
        },
        {
          icon: 'fas fa-check-square',
          title: '24/7 Support Help Center'
        },
        {
          icon: 'fas fa-check-square',
          title: 'Customer Service & Operations'
        }
      ]
    }
  }
}
</script>
