// src/react/components/home-section/landing-page4/about/index.js
import React from 'react';

import { SectionTitle, CheckboxList} from '../../../xamin';
import Link from 'next/link';
import Image from 'next/image';

import img from "../../../../public/assets/images/about-us/13.png"
import img1 from "../../../../public/assets/images/about-us/13.png"
class   Index extends React.Component {
    constructor(props) {
        super(props);
        this.state={
            checkList:[
                'Advance Advisory Team',
                'Professional Consulting Services',
                '24/7 Support Help Center',
                'Customer Service &amp; Operations'
            ]
        }
    }

    render() {
        let { checkList } = this.state;
        return (
            <>
                <section>
                    <div className="container">
                        <div className="row">
                           <div  className="col-lg-6 wow fadeInUp align-items-center">
                                 <SectionTitle
                                    className={"title-box wow fadeInUp text-left"}
                                    spanclass={"title-design"}
                                    link={"About us"}
                                    title={"Human Behaviour, Data Science"}
                                    subTitle ={"It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout."}
                                />
                                  <CheckboxList text={"text-left"} items={checkList} />
                                  <div className=" text-left mt-5 ">
                                    <Link className="button button-icon" href="#"> <span className="btn-effect"> Read More</span> </Link>
                                 </div>
                           </div>
                            <div className="col-lg-6  wow fadeInUp ">
                                 <Image  src={img} className="attachment-full" alt="" sizes="100vw" />
                            </div>
                        </div>
                        <div className="row mt-5">
                             <div className="col-lg-6  wow fadeInUp ">
                                 <Image  src={img1} className="attachment-full" alt="" sizes="100vw" />
                            </div>
                            <div  className="col-lg-6 wow fadeInUp align-items-center">
                                 <SectionTitle
                                    className={"title-box wow fadeInUp text-left"}
                                    spanclass={"title-design"}
                                    link={"About us"}
                                    title={"Focused on Actionable Insights"}
                                    subTitle ={"It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout."}
                                />
                                  <CheckboxList text={"text-left"} items={checkList} />
                                  <div className=" text-left mt-5 ">
                                    <Link className="button button-icon" href="#"> <span className="btn-effect"> Read More</span> </Link>
                                 </div>
                           </div>
                        </div>
                    </div>
                </section>
            </>
        );
    }
}

export default Index;

// src/vue/components/LandingPage18/About.vue
<template>
  <section class="position-relative overview-block-pb overflow-hidden">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 mb-5 mb-lg-0 wow fadeInUp align-items-center">
          <div class="title-box wow fadeInUp  text-left">
            <span class="title-design">About Us Our Company</span>
            <h2>What is analytics?</h2>
            <p>It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout.</p>
          </div>
          <div class="text-left  ">
            <ul class="iq-list">
              <li><i class="fa fa-check-square-o" /><span>Advance Advisory Team</span></li><li><i class="fa fa-check-square-o" /><span>Professional Consulting Services</span></li><li><i class="fa fa-check-square-o" /><span> 24/7 Support Help Center</span></li><li><i class="fa fa-check-square-o" /><span>Customer Service &amp; Operations</span></li>
            </ul>
          </div>
          <div class=" text-left mt-5 ">
            <a class="button blue-btn button-icon" href="/landing-page-18"><span class="btn-effect"> Read More</span></a>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="iq-image">
            <img src="/assets/images/about-us/23.png" class="img-fluid" alt="">
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {
  name: 'About'
}
</script>
