// src/react/components/home-section/landing-page1/about/index.js
import React from 'react';
import Link from "next/link";

import { SectionStyle1, SectionTitle, CheckboxList} from '../../../xamin';

import img from "../../../../public/assets/images/about-us/02.png"
import Image from 'next/image';

class Index extends React.Component {
    constructor(props) {
        super(props);
        this.state= {
            checklist: [
                "Advance Advisory Team",
                "Professional Consulting Services",
                "24/7 Support Help Center",
                "Customer Service &amp; Operations",
            ]
        };
    }

    render() {
     
        return (
            <>
                <SectionStyle1 rowReverse={true}>
                    <Image className="about-box-img" src={img}  alt="drive01" />
                    <div className="col-lg-6">
                    </div>
                    <div className="col-lg-6 wow fadeInUp align-items-center">
                        <div  className="title-box wow fadeInUp text-left">
                                <SectionTitle
                                    link ="About us"
                                    title="Focused on Actionable Insights"
                                    subTitle="It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout."
                                    className = "title-box wow fadeInUp text-left"
                                    spanclass="title-design"
                                    />
                        </div>
                        
                        <CheckboxList text={"text-left"} items={this.state.checklist} />

                        <div className=" text-left mt-5 ">
                            <Link href="/about-us-1">
                                <span className="button button-icon" > <span className="btn-effect"> Read More</span> </span>
                            </Link>
                        </div>
                    </div>
                </SectionStyle1>     
            </>
        );
    }
}

export default Index;

// src/vue/components/LandingPage18/About.vue
<template>
  <section class="position-relative overview-block-pb overflow-hidden">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 mb-5 mb-lg-0 wow fadeInUp align-items-center">
          <div class="title-box wow fadeInUp  text-left">
            <span class="title-design">About Us Our Company</span>
            <h2>What is analytics?</h2>
            <p>It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout.</p>
          </div>
          <div class="text-left  ">
            <ul class="iq-list">
              <li><i class="fa fa-check-square-o" /><span>Advance Advisory Team</span></li><li><i class="fa fa-check-square-o" /><span>Professional Consulting Services</span></li><li><i class="fa fa-check-square-o" /><span> 24/7 Support Help Center</span></li><li><i class="fa fa-check-square-o" /><span>Customer Service &amp; Operations</span></li>
            </ul>
          </div>
          <div class=" text-left mt-5 ">
            <a class="button blue-btn button-icon" href="/landing-page-18"><span class="btn-effect"> Read More</span></a>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="iq-image">
            <img src="/assets/images/about-us/23.png" class="img-fluid" alt="">
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {
  name: 'About'
}
</script>
