// src/react/components/home-section/landing-page3/services/index.js
import React from 'react';

import { CheckboxList } from '../../../xamin';
import Link from 'next/link';

class Index extends React.Component {
    constructor(props) {
        super(props);
        this.state={
            tabs:[
                {
                    href:'tab-software-development',
                    title:'Software Development',
                    subTitle:'Choose Your Software Development Service',
                    description:'Tame your big data through robust solutions that empower data collection, storage,processing and analysis.'
                },
                {
                    href:'tab-application-services',
                    title:'Application Services',
                    subTitle:'Choose Your Application Service',
                    description:'Tame your big data through robust solutions that empower data collection, storage,processing and analysis.'
                },
                {
                    href:'tab-data-analytics',
                    title:'Data Analytics',
                    subTitle:'Choose Your Data Analytics Service',
                    description:'Tame your big data through robust solutions that empower data collection, storage,processing and analysis.'
                },
                {
                    href:'tab-help-desk-services',
                    title:'Help Desk Services',
                    subTitle:'Choose Your Help Desk Service',
                    description:'Tame your big data through robust solutions that empower data collection, storage,processing and analysis.'
                }
            ],
            checkList:[
                "Advance Advisory Team",
                "Professional Consulting Services",
                "24/7 Support Help Center",
                "Customer Service &amp; Operations",
                "There are many variations of passages."
            ]
        }
    }

    render() {
        let { tabs, checkList } = this.state;
        return (
            <>
                <section className="iq-bg-over">
                    <div className="container">
                        <div className="row">
                            <div className="col-md-4">
                                <div className="custom-tab">
                                    <ul className="nav nav-pills text-center flex-column mb-5 mb-md-0" id="pills-tab" role="tablist" aria-orientation="vertical">
                                        {
                                            tabs.map((tab,index) => (
                                                <li key={index} className="nav-item w-inherit">
                                                    <Link className={"nav-link w-100"+(index==0 ? ' show active' : '')} data-toggle="pill" href={'#'+tab.href} role="tab" aria-selected={index==0 ? 'true' : 'false'}>
                                                        <h5 className="tab-title">{tab.title}</h5>
                                                    </Link>
                                                </li>
                                            ))
                                        }
                                    </ul>
                                </div>
                            </div>
                            <div className="col-md-8">
                                <div className="tab-content">
                                    {
                                        tabs.map((tab,index) => (
                                            <div key={index} id={tab.href} className={"tab-pane fade "+(index==0 ? " active show" : '')}>
                                                <h3 className="pb-3">{tab.subTitle}</h3>
                                                <p>{tab.description}</p>
                                                <CheckboxList className="column-2" items={checkList} />
                                            </div>
                                        ))
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </>
        );
    }
}

export default Index;

// src/vue/components/LandingPage18/Services.vue
<template>
  <section class="pt-0 xamin-background overflow-hidden">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="title-box wow fadeInUp text-center">
            <span class="title-design">OUR SERVICES</span>
            <h2>Streamline your workflow.</h2>
          </div>
        </div>
      </div>
      <div class="row custom-tab verticaltab3">
        <div class="col-md-6">
          <div class="col-lg-12 col-md-12 ">
            <ul id="pills-tab" class="nav nav-pills nav-pills-style-3 mb-5" role="tablist" aria-orientation="vertical">
              <li v-for="(service,index) in services" :key="index" class="nav-item">
                <a :class="service.class" data-toggle="pill" :href="service.id" role="tab" aria-selected="true">
                  <div class="media">
                    <img :src="service.src" alt="tab-image" class="img-fluid">
                    <div class="media-body">
                      <h5 class="mb-2 active-title">{{ service.title }}</h5>
                      <p class="mb-0">{{ service.desc }}</p>
                    </div>
                  </div>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-6 tab-content">
          <div v-for="(tab,index) in tabs" :id="tab.id" :key="index" :class="tab.class">
            <div class="xamin-right-img-wm">
              <img alt="#" :src="tab.src" class="attachment-full img-fluid">
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {
  name: 'Services',
  data () {
    return {
      services: [ {
        id: '#tab-software-development',
        src: '/assets/images/services/6-1.png',
        title: 'Capture',
        desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        class: 'nav-link show active'
      },
      {
        id: '#tab-application-services',
        src: '/assets/images/services/6-2.png',
        title: 'Content',
        desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        class: 'nav-link'
      },
      {
        id: '#tab-data-analytics',
        src: '/assets/images/services/6-3.png',
        title: 'Analysis',
        desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        class: 'nav-link'
      },
      {
        id: '#tab-help-desk-services',
        src: '/assets/images/services/6-4.png',
        title: 'Data',
        desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        class: 'nav-link'
      }
      ],
      tabs: [ {
        id: 'tab-software-development',
        src: '/assets/images/services/30.png',
        class: 'tab-pane fade active show'
      },
      {
        id: 'tab-application-services',
        src: '/assets/images/services/14.png',
        class: 'tab-pane fade'
      },
      {
        id: 'tab-data-analytics',
        src: '/assets/images/services/13.png',
        class: 'tab-pane fade'
      },
      {
        id: 'tab-help-desk-services',
        src: '/assets/images/services/14.png',
        class: 'tab-pane fade'
      }
      ]
    }
  }
}
</script>>
