// src/vue/components/DataVisualization/Service.vue
<template>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-sm-12 sidebar-service-left">
          <CardStyle5 :card-menu="menu_item" />
          <div class="testimonial-widget-menu widget">
            <CardStyle3 :card-content="list" card-class="owl-carousel owl-loaded owl-drag"/>
          </div>
          <div class="widget get-file">
            <h2 class="widget-title">Downloads</h2>
            <a href="#">
              <ul class="list-inline download-item">
                <li class="list-inline-item"> <i class="far fa-file-pdf"></i><span class="ml-3">PDF download</span> </li>
              </ul>
            </a>
          </div>
          <div class="widget get-file mb-5">
            <a href="#">
              <ul class="list-inline download-item">
                <li class="list-inline-item"><i class="far fa-file-pdf"></i><span class="ml-3">Company White Paper</span></li>
              </ul>
            </a>
          </div>
        </div>
        <div class="col-lg-8 col-sm-12 pt-5 pt-lg-0">
          <div class="row iq-pb-45">
            <div class="col-sm-12 col-lg-6 col-md-6">
              <div class="no-margin services-finance-img text-center">
                <img width="400" height="400" src="/assets/images/about-us/04.png" class="attachment-full" alt=""  />
              </div>
            </div>
            <div class="mt-5 mt-lg-0 mt-md-0 col-sm-12 col-lg-6 col-md-6">
              <h3>Our Services</h3>
              <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration.</p>
              <div class="text-left">
                <ul class="iq-list">
                    <li><i class="fas fa-check-square"></i><span>Efficiently manage and govern ongoing operations of analytics processes</span></li>
                    <li><i class="fas fa-check-square"></i><span>Access on-demand data scientists to quickly scale your analytics team</span></li>
                    <li><i class="fas fa-check-square"></i><span>Rapid time to insight</span></li>
                    <li><i class="fas fa-check-square"></i><span>Lower operating cost and business risk</span></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="row">
            <div v-for="(item,index) in items1" :key="index" class="col-md-6">
                <div class="service-box my-3 wow fadeInUp text-left">
                  <i aria-hidden="true" :class="item.class"></i>
                  <div class="service-detail align-self-center">
                      <h4 class="mb-2">{{ item.title }}</h4>
                      <p>{{ item.subtitle }}</p>
                  </div>
                </div>
            </div>
          </div>
          <div class="row iq-pb-30">
            <div v-for="(item,index) in items2" :key="index" class="col-md-6">
                <div class="service-box my-3 wow fadeInUp text-left">
                  <i aria-hidden="true" :class="item.class"></i>
                  <div class="service-detail align-self-center">
                      <h4 class="mb-2">{{ item.title }}</h4>
                      <p>{{ item.subtitle }}</p>
                  </div>
                </div>
            </div>
          </div>
          <div class="row iq-pb-45">
            <div class="col-sm-12">
              <div>
                <canvas id="canvas" class="data-visualization-chart"></canvas>
              </div>
              <ul id="js-legend" class="chart-legend"></ul>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <h3 class="text-left mb-4">Service development Specialist</h3>
              <div class="row">
                <div class="col-md-12">
                  <div class="owl-carousel owl-loaded owl-drag" data-dots="false" data-nav="false" data-items="3" data-items-laptop="3" data-items-tab="2" data-items-mobile="2" data-items-mobile-sm="1" data-autoplay="true" data-loop="true" data-margin="30">
                    <div class="item text-left" v-for="(item, index) in team" :key="index" >
                      <div class="iq-team">
                        <div class="iq-team-img"> <img :src="item.media" class="img-fluid" alt="#1"> </div>
                        <div class="iq-share">
                          <div class="slideouticons">
                            <label class="mainlabel"><i class="fa fa-share-alt"></i></label>
                            <div class="iconswrapper">
                              <ul>
                                <li><a href="#"><i class="fa-brands fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                              </ul>
                            </div>
                          </div>
                        </div>
                        <div class="iq-team-info text-center">
                          <a>
                            <h5>{{ item.title }}</h5>
                          </a>
                          <span>{{ item.subtitle }}</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
import CardStyle3 from '../themes/Card/CardStyle3.vue';
import CardStyle5 from '../themes/Card/CardStyle5.vue';
  export default {
    name: 'Service',
    components:{
      CardStyle3,
      CardStyle5,
    },
    data() {
      return {
        list:[
          {
            title: 'Jack White',
            subtitle: 'CEO',
            description: 'Richard McClintock, a Latin professor at Hampden-Sydney consectetur adip isicing elit, sed dolore magna aliqua hampden. Latin professor at Hampden-Sydney consectetur.',
            src: '/assets/images/testimonials/1.jpg'
          },
          {
            title: 'Walhan Bobe',
            subtitle: 'Business Adviser',
            description: '“Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium incididunt ut labore et dolore Sed ut perspiciatis error. Perspiciatis unde omnis iste.”',
            src: '/assets/images/testimonials/2.jpg'
          },
          {
            title: 'Mark McManus',
            subtitle: 'COO',
            description: '“Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.”',
            src: '/assets/images/testimonials/3.jpg'
          }
        ],
        images: [
          {
            src: '/assets/images/about-us/04.png'
          },
          {
            src: '/assets/images/about-us/03.png'
          },
          {
            src: '/assets/images/about-us/04.png'
          },
          {
            src: '/assets/images/about-us/03.png'
          },
          {
            src: '/assets/images/about-us/04.png'
          },
          {
            src: '/assets/images/about-us/03.png'
          }
        ],
        menu_item: [
          {
            title: 'Data Analytics',
            class: 'nav-link',
            href: 'data-analytics'
          },
          {
            title: 'Managed Analytics',
            class: 'nav-link',
            href: 'managed-analytics'
          },
          {
            title: 'Big Data Services',
            class: 'nav-link',
            href: 'big-data-services'
          },
          {
            title: 'Data Science Consulting',
            class: 'nav-link',
            href: 'data-science-consulting'
          },
          {
            title: 'Business Intelligence',
            class: 'nav-link',
            href: 'business-intelligence'
          },
          {
            title: 'Data Visualization',
            class: 'nav-link current-menu-item',
            href: 'data-visualization'
          },
          {
            title: 'Data Management',
            class: 'nav-link',
            href: 'data-management'
          },
          {
            title: 'Artificial Intelligence',
            class: 'nav-link',
            href: 'artificial-intelligence'
          }
        ],
        items1 : [
          {
            class: 'flaticon flaticon-growth',
            title: 'Big Data Consulting',
            subtitle: 'It is a long established fact that a reader will be distracted.'
          },
          {
            class: 'flaticon flaticon-grouping',
            title: 'Apache Hadoop',
            subtitle: 'It is a long established fact that a reader will be distracted.'
          }
        ],
        items2 : [
          {
            class: 'flaticon flaticon-cloud-1',
            title: 'Apache Spark',
            subtitle: 'It is a long established fact that a reader will be distracted.'
          },
          {
            class: 'flaticon flaticon-box',
            title: 'Apache Cassandra',
            subtitle: 'It is a long established fact that a reader will be distracted.'
          }
        ],
        team: [
          {
            title: 'Anna Mull',
            subtitle: 'COO',
            media: '/assets/images/team/1.jpg'
          },
          {
            title: 'Petey Cruiser',
            subtitle: 'Project Manager',
            media: '/assets/images/team/2.jpg'
          },
          {
            title: 'Greta Life',
            subtitle: 'CFO',
            media: '/assets/images/team/3.jpg'
          },
          {
            title: 'Marcash Dane',
            subtitle: 'Project Manager',
            media: '/assets/images/team/4.jpg'
          },
          {
            title: 'Handry White',
            subtitle: 'Project Manager',
            media: '/assets/images/team/5.jpg'
          }
        ]
      }
    }
  }
</script>

// src/react/components/home-section/landing-page1/service/index.js
import React from 'react';

import { SectionTitle,SectionStyle3, CardStyle13 } from '../../../xamin';


class Index extends React.Component {

    constructor(props) {
        super(props);

        this.state = {
            cardData: [
                {
                    images:  require('../../../../public/assets/images/testimonials/3.jpg'),
                    name: "Mark McManus",
                    position: "COO",
                    description: "“Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.” ",
                },
                {
                    images:  require('../../../../public/assets/images/testimonials/2.jpg'),
                    name: "Jack White",
                    position: "CEO",
                    description: "“Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.” ",
                },
                {
                    images:  require('../../../../public/assets/images/testimonials/3.jpg'),
                    name: "Jack McManus",
                    position: "CTO",
                    description: "“Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.” ",
                }
               
            ]
        }

    }

    render() {
        let { cardData } = this.state;
        return (
            <>
                <SectionStyle3 id="our-service" >
                <div className="row">
                     <div className="col-sm-12 wow fadeInUp">
                        <SectionTitle
                                link="OUR SERVICES"
                                className = "title-box wow fadeInUp text-center"
                                title="What Our Clients Say"
                                spanclass="title-design"
                        />
                    </div>
                </div>
                <div className="row">
                    <div className="col-md-12  wow fadeInUp">
                            <div className="owl-carousel testimonial-style owl-loaded owl-drag" data-dots="true" data-nav="false" data-autoplay="false" data-loop="true" data-items="1" data-items-laptop="1" data-items-tab="1" data-items-mobile="1" data-items-mobile-sm="1" data-margin="30">
                                {
                                    cardData.map((card, index) => (
                                        <CardStyle13
                                            key={index}
                                            image={card.images}
                                            title={card.name}
                                            subTitle={card.position}
                                            description={card.description}
                                        />
                                    ))
                                }
                            </div>
                    </div>
               </div>

                </SectionStyle3>
            </>
        );
    }

}

export default Index;
