// src/vue/components/LandingPage3/GetStarted.vue
<template>
  <section class="position-relative overflow-hidden">
    <img src="/assets/images/about-us/11.png" class="about-right-box-img" alt="">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 wow fadeInUp align-items-center">
          <div class="title-box wow fadeInUp text-left">
            <span class="title-design">LETS GET STARTED  </span>
            <h2>Are you ready for a better, more productive business?</h2>
            <p>The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.</p>
          </div>
          <div class=" text-left mt-5 ">
              <a class="button button-icon" href="#"> <span class="btn-effect"> Read More</span> </a>
          </div>
        </div>
        <div class="col-lg-6"> </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {
    name:'GetStarted'
}
</script>

// src/react/components/home-section/landing-page3/get-started/index.js
import React from 'react';
import Link from "next/link";
import { SectionTitle } from '../../../xamin';
import Image from 'next/image';

import img from "../../../../public/assets/images/about-us/08.png"
class Index extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <>
                <section className="position-relative overflow-hidden pt-0">
                    <Image src={img} className="about-right-box-img" alt="" />
                        <div className="container">
                            <div className="row">
                                <div className="col-lg-6 wow fadeInUp align-items-center">
                                    <SectionTitle
                                        className="title-box wow fadeInUp text-left"
                                        link="LETS GET STARTED"
                                        spanclass="title-design"
                                        title="Are you ready for a better, more productive business?"
                                        subTitle="The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English."
                                    />
                                    <div className=" text-left mt-5 ">
                                        <Link  href="/about-us-1" className="button button-icon">
                                            <span className="btn-effect"> Read More</span>
                                        </Link>
                                    </div>
                                </div>
                                <div className="col-lg-6"></div>
                            </div>
                        </div>
                </section>
            </>
        );
    }
}

export default Index;
