// src/react/components/home-section/landing-page3/process/index.js
import React from 'react';

import { SectionTitle, CardStyle1 } from '../../../xamin';

class Index extends React.Component {
    constructor(props) {
        super(props);
        this.state ={
            items:[
                {
                    media: require("../../../../public/assets/images/services/01.png"),
                    title: "Data for all your people",
                    text :"it is a long established fact that a reader will be distracted by the of readable"

                },
                {
                    media: require("../../../../public/assets/images/services/02.png"),
                    title: "A new breed of AI",
                    text :"it is a long established fact that a reader will be distracted by the of readable"
                },
                {
                    media: require("../../../../public/assets/images/services/03.png"),
                    title: "Analytics business",
                    text :"it is a long established fact that a reader will be distracted by the of readable"
                }
            ]
        }
    }

    render() {
        const {items } = this.state;

        return (
            <>
                <section>
                    <div className="container">
                        <div className="row">
                            <div className="col-md-12">
                                <SectionTitle
                                    link="How it works ?"
                                    title="How Does Xamin Works"
                                    className = "title-box wow fadeInUp text-center"
                                    spanclass="title-design"
                                />
                            </div>
                        </div>
                        <div className="row">
                            {
                                items.map((item,index) => (
                                    <div key={'p1'+index} className="col-md-4 col-sm-12">
                                        <div className={"xamin-process xamin-circle wow fadeInUp text-center "+((index<this.state.items.length-1) ? "right" : '')}>
                                            <CardStyle1
                                                media={item.media}
                                                title ={item.title}
                                                text= {item.text}
                                            />
                                        </div>
                                    </div>
                                ))
                            }
                        </div>
                    </div>
                </section>

            </>
        );
    }
}

export default Index;

// src/vue/components/LandingPage3/Process.vue
<template>
  <section class="xamin-custom-bg">
    <div class="container">
      <div class="row ">
        <div class="col-md-12">
          <div class="title-box wow fadeInUp text-center">
            <span class="title-design">PROCESS</span>
            <h2>Our Software Testing Process</h2>
          </div>
        </div>
      </div>
      <div class="row ">
        <div class="col-md-4 col-sm-12">
          <div class="xamin-process xamin-circle right wow fadeInUp text-center" data-wow-delay="0.6s">
            <div class="circle-effect"> <img src="/assets/images/services/01.png" alt="fancybox"> </div>
            <h5 class="mb-2">Planning</h5>
            <p class="mb-0">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
          </div>
        </div>
        <div class="col-md-4 col-sm-12 mt-4 mt-md-0">
          <div class="xamin-process xamin-circle right wow fadeInUp text-center" data-wow-delay="0.6s">
            <div class="circle-effect"> <img src="/assets/images/services/02.png" alt="fancybox"> </div>
            <h5 class="mb-2">Design and Execution</h5>
            <p class="mb-0">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
          </div>
        </div>
        <div class="col-md-4 col-sm-12 mt-4 mt-md-0">
          <div class="xamin-process xamin-circle wow fadeInUp text-center" data-wow-delay="0.6s">
            <div class="circle-effect"> <img src="/assets/images/services/03.png" alt="fancybox"> </div>
            <h5 class="mb-2">Report and Signout</h5>
            <p class="mb-0">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {
    name:'Process',
}
</script>
