// src/react/components/home-section/landing-page3/services/index.js
import React from 'react';

import { CheckboxList } from '../../../xamin';
import Link from 'next/link';

class Index extends React.Component {
    constructor(props) {
        super(props);
        this.state={
            tabs:[
                {
                    href:'tab-software-development',
                    title:'Software Development',
                    subTitle:'Choose Your Software Development Service',
                    description:'Tame your big data through robust solutions that empower data collection, storage,processing and analysis.'
                },
                {
                    href:'tab-application-services',
                    title:'Application Services',
                    subTitle:'Choose Your Application Service',
                    description:'Tame your big data through robust solutions that empower data collection, storage,processing and analysis.'
                },
                {
                    href:'tab-data-analytics',
                    title:'Data Analytics',
                    subTitle:'Choose Your Data Analytics Service',
                    description:'Tame your big data through robust solutions that empower data collection, storage,processing and analysis.'
                },
                {
                    href:'tab-help-desk-services',
                    title:'Help Desk Services',
                    subTitle:'Choose Your Help Desk Service',
                    description:'Tame your big data through robust solutions that empower data collection, storage,processing and analysis.'
                }
            ],
            checkList:[
                "Advance Advisory Team",
                "Professional Consulting Services",
                "24/7 Support Help Center",
                "Customer Service &amp; Operations",
                "There are many variations of passages."
            ]
        }
    }

    render() {
        let { tabs, checkList } = this.state;
        return (
            <>
                <section className="iq-bg-over">
                    <div className="container">
                        <div className="row">
                            <div className="col-md-4">
                                <div className="custom-tab">
                                    <ul className="nav nav-pills text-center flex-column mb-5 mb-md-0" id="pills-tab" role="tablist" aria-orientation="vertical">
                                        {
                                            tabs.map((tab,index) => (
                                                <li key={index} className="nav-item w-inherit">
                                                    <Link className={"nav-link w-100"+(index==0 ? ' show active' : '')} data-toggle="pill" href={'#'+tab.href} role="tab" aria-selected={index==0 ? 'true' : 'false'}>
                                                        <h5 className="tab-title">{tab.title}</h5>
                                                    </Link>
                                                </li>
                                            ))
                                        }
                                    </ul>
                                </div>
                            </div>
                            <div className="col-md-8">
                                <div className="tab-content">
                                    {
                                        tabs.map((tab,index) => (
                                            <div key={index} id={tab.href} className={"tab-pane fade "+(index==0 ? " active show" : '')}>
                                                <h3 className="pb-3">{tab.subTitle}</h3>
                                                <p>{tab.description}</p>
                                                <CheckboxList className="column-2" items={checkList} />
                                            </div>
                                        ))
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </>
        );
    }
}

export default Index;

// src/vue/components/LandingPage3/Services.vue
<template>
  <section class="iq-bg-over">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="custom-tab">
            <ul class="nav nav-pills text-center flex-column mb-5 mb-md-0" id="pills-tab" role="tablist" aria-orientation="vertical">
              <li class="nav-item w-inherit ">
                <a class="nav-link w-100 active" data-toggle="pill" href="#tab-software-development" role="tab" aria-selected="true"><h5 class="tab-title">Software Development</h5></a>
              </li>
              <li class="nav-item w-inherit">
                <a class="nav-link w-100" data-toggle="pill" href="#tab-application-services" role="tab" aria-selected="false"><h5 class="tab-title">Application Services</h5></a>
              </li>
              <li class="nav-item w-inherit">
                <a class="nav-link w-100" data-toggle="pill" href="#tab-data-analytics" role="tab" aria-selected="false"><h5 class="tab-title">Data Analytics</h5></a>
              </li>
              <li class="nav-item w-inherit">
                <a class="nav-link w-100" data-toggle="pill" href="#tab-help-desk-services" role="tab" aria-selected="false"><h5 class="tab-title">Help Desk Services</h5></a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-8">
          <div class="tab-content">
            <div id="tab-software-development" class="tab-pane fade active show">
              <h3 class="pb-3">Choose Your Software Development Service</h3>
              <p>Tame your big data through robust solutions that empower data collection, storage,processing and analysis.</p>
              <ul class="iq-list column-2">
                <li><i class="fas fa-check-square"></i>Advance Advisory Team</li>
                <li><i class="fas fa-check-square"></i>Professional Consulting Services</li>
                <li><i class="fas fa-check-square"></i>24/7 Support Help Center</li>
                <li><i class="fas fa-check-square"></i>Customer Service &amp; Operations</li>
                <li><i class="fas fa-check-square"></i>There are many variations of passages.</li>
              </ul>
            </div>
            <div id="tab-application-services" class="tab-pane fade ">
              <h3 class="pb-3">Choose Your Application Service</h3>
              <p>Tame your big data through robust solutions that empower data collection, storage,processing and analysis.</p>
              <ul class="iq-list column-2">
                <li><i class="fas fa-check-square"></i>Advance Advisory Team</li>
                <li><i class="fas fa-check-square"></i>Professional Consulting Services</li>
                <li><i class="fas fa-check-square"></i>24/7 Support Help Center</li>
                <li><i class="fas fa-check-square"></i>Customer Service &amp; Operations</li>
                <li><i class="fas fa-check-square"></i>There are many variations of passages.</li>
              </ul>
            </div>
            <div id="tab-data-analytics" class="tab-pane fade">
              <h3 class="pb-3">Choose Your Data Analytics Service</h3>
              <p>Tame your big data through robust solutions that empower data collection, storage,processing and analysis.</p>
              <ul class="iq-list column-2">
                <li><i class="fas fa-check-square"></i>Advance Advisory Team</li>
                <li><i class="fas fa-check-square"></i>Professional Consulting Services</li>
                <li><i class="fas fa-check-square"></i>24/7 Support Help Center</li>
                <li><i class="fas fa-check-square"></i>Customer Service &amp; Operations</li>
                <li><i class="fas fa-check-square"></i>There are many variations of passages.</li>
              </ul>
            </div>
            <div id="tab-help-desk-services" class="tab-pane fade">
              <h3 class="pb-3">Choose Your Help Desk Service</h3>
              <p>Tame your big data through robust solutions that empower data collection, storage,processing and analysis.</p>
              <ul class="iq-list column-2">
                <li><i class="fas fa-check-square"></i>Advance Advisory Team</li>
                <li><i class="fas fa-check-square"></i>Professional Consulting Services</li>
                <li><i class="fas fa-check-square"></i>24/7 Support Help Center</li>
                <li><i class="fas fa-check-square"></i>Customer Service &amp; Operations</li>
                <li><i class="fas fa-check-square"></i>There are many variations of passages.</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {
    name: 'Services'
}
</script>
