// src/vue/components/LandingPage14/About.vue
<template>
  <section class="position-relative overview-block-pb iq-pb-70">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="title-box wow fadeInUp  text-center">
            <span class="title-design">Our Services</span>
            <h2>How it helps you succeed</h2>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-lg-4 col-sm-6">
          <div class="iq-service-box shadow-on-hover wow fadeInUp  text-center" data-wow-delay="0.4s">
            <div class="fancy-info">
              <div class="fancy_img">
                <img src="/assets/images/services/03.png" class="img-fluid" alt="fancybox">
              </div>
              <h4 class="mt-4 mb-3 title">
                Trace Analysis
              </h4><p class="">
                Many publishing packages and web page editors now use Lorem.
              </p><a class="button btn-simple" href="#"><span class="btn-effect"> Read More</span></a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 col-sm-6">
          <div class="iq-service-box shadow-on-hover wow fadeInUp  text-center" data-wow-delay="0.4s">
            <div class="fancy-info">
              <div class="fancy_img">
                <img src="/assets/images/services/04.png" class="img-fluid" alt="fancybox">
              </div>
              <h4 class="mt-4 mb-3 title">
                Proprietary Research
              </h4><p class="">
                It is a long established fact that a reader will be distracted.
              </p><a class="button btn-simple" href="#"><span class="btn-effect"> Read More</span></a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 col-sm-6">
          <div class="iq-service-box shadow-on-hover wow fadeInUp  text-center" data-wow-delay="0.4s">
            <div class="fancy-info">
              <div class="fancy_img">
                <img src="/assets/images/services/01.png" class="img-fluid" alt="fancybox">
              </div>
              <h4 class="mt-4 mb-3 title">
                Data Analysis
              </h4><p class="">
                Many publishing packages and web page editors now use Lorem.
              </p><a class="button btn-simple" href="#"><span class="btn-effect"> Read More</span></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {
  name: 'About'
}
</script>

// src/react/components/home-section/landing-page7/about/index.js
import React from 'react';

import { AboutStyle, SectionTitle, CheckboxList} from '../../../xamin';
import Link from 'next/link';
import Image from 'next/image';

import img from "../../../../public/assets/images/about-us/06.png"
class   Index extends React.Component {
    constructor(props) {
        super(props);
        this.state={
            checkList:[
                'Polarity: if the speaker express a positive or negative opinion,',
                'Subject: the thing that is being talked about',
                'Opinion holder: the person, or entity that expresses the opinion.',
            ]
        }
    }

    render() {
        let { checkList } = this.state;
        return (
            <>
                <section className="position-relative">
                
                     <Image src={img} className="about-box-img" />
                    <div className="container">
                        <div className="container">
                            <div className="row">
                            <div className="col-lg-6"> </div>
                                <div className="col-lg-6 wow fadeInUp align-items-center">
                                    <SectionTitle
                                        link ="About us"
                                        title="What is Sentiment Analysis?"
                                        subTitle="It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.
                                        Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy."
                                        className = "title-box wow fadeInUp text-left"
                                        spanclass="title-design"
                                    />
                                     <CheckboxList text={"text-left"} items={checkList} />
                                     <div className=" text-left mt-5 ">
                                          <Link className="button button-icon" href="about-us.html"> <span className="btn-effect"> View Details</span> </Link>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                    </section>

                

                

              
            </>
        );
    }
}

export default Index;
