// src/react/components/xamin/Portfolio/index.js
import React from 'react';
import Link from "next/link";
import { Item } from '../../../constants/portfolio-item';
import Image from 'next/image';

class Index extends React.Component{
    constructor(props) {
        super(props);
        this.state = {
            items : Item
        }
    }

    render() {
        let items = this.state.items;
        items=items.filter((item)=>{
            if(this.props.filterdata=='all'){
                return true;
            }
            return item.filterClass.includes(this.props.filterdata);
        });
        return(
            <>

                { items.map((itemData,index) => (
                    <div key={index} className={"iq-masonry-item item "+itemData.filterClass}>
                        <div className="iq-portfolio">
                            <Link href={itemData.link} >
                            <span className="iq-portfolio-img">
                                    <Image width="1260" height="954"  src={itemData.image}     className="attachment-post-thumbnail size-post-thumbnail wp-post-image"   alt="" />
                            </span>
                            </Link>
                            <div className="iq-portfolio-content  text-center">
                                <div className="details-box clearfix">
                                    <div className="consult-details">
                                        <Link href={itemData.link}>
                                        <span>
                                                <h5 className="text-hover">{itemData.title}</h5>
                                        </span>
                                        </Link>
                                        <p className="desc mb-0">{itemData.description}</p>
                                       
                                    </div>
                                    {/* <div className="mb-0 portfolio-tag"><ul> <li>Html</li> <li>Video</li></ul></div> */}
                                </div>
                            </div>
                        </div>
                    </div>
                )) }
            </>
        )
    }
}
export default Index;

// src/vue/components/LandingPage22/Portfolio.vue
<template>
  <section class="overview-block-ptb iq-pb-70">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 fadeInUp  animated">
          <div class="title-box wow fadeInUp text-center">
            <span class="title-design">CASE STUDIES</span>
            <h2>We have Completed Thousand of Projects</h2>
          </div>
        </div>
        <div class="col-md-12">
          <div id="features" class="iq-amazing-tab iq-minimal-tab wow fadeInUp" data-wow-delay="1s">
            <div class="row">
              <div class="col-lg-12">
                <ul id="myTab" class="nav  justify-content-center" role="tablist">
                  <li>
                    <a
                      id="all-tab"
                      class="nav-link show active"
                      data-toggle="tab"
                      href="#all"
                      role="tab"
                      aria-selected="true"
                    >All<span class="post_no">8</span></a>
                  </li>
                  <li><a id="design-tab" class="nav-link" data-toggle="tab" href="#design" role="tab">Design<span class="post_no">3</span></a></li>
                  <li><a id="html-tab" class="nav-link" data-toggle="tab" href="#html" role="tab">HTML<span class="post_no">2</span></a></li>
                  <li><a id="photography-tab" class="nav-link" data-toggle="tab" href="#photography" role="tab">Photography<span class="post_no">3</span></a></li>
                  <li><a id="video-tab" class="nav-link" data-toggle="tab" href="#video" role="tab">Video<span class="post_no">1</span></a></li>
                </ul>
              </div>
            </div>
            <div class="tab-content ">
              <div id="all" class="tab-pane active show">
                <div class="row">
                  <div class="col-lg-4 col-md-6 text-left align-self-center">
                    <div class="iq-masonry-item item video ">
                      <div class="iq-portfolio">
                        <a href="/portfolio-detail" class="iq-portfolio-img"><img width="1260" height="954" src="/assets/images/about-us/01.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></a>
                        <div class="iq-portfolio-content  text-center">
                          <div class="details-box clearfix">
                            <div class="consult-details">
                              <a href="/portfolio-detail">
                                <h5 class="text-hover">Memory Statistics</h5>
                              </a>
                              <p class="mb-0">
                                Photography
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 text-left align-self-center">
                    <div class="iq-masonry-item item html ">
                      <div class="iq-portfolio">
                        <a href="/portfolio-detail" class="iq-portfolio-img"><img width="1260" height="954" src="/assets/images/about-us/03.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></a>
                        <div class="iq-portfolio-content  text-center">
                          <div class="details-box clearfix">
                            <div class="consult-details">
                              <a href="/portfolio-detail">
                                <h5 class="text-hover">Text Analytics</h5>
                              </a>
                              <p class="mb-0">
                                HTML
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 text-left align-self-center">
                    <div class="iq-masonry-item item html ">
                      <div class="iq-portfolio">
                        <a href="/portfolio-detail" class="iq-portfolio-img"><img width="1260" height="954" src="/assets/images/about-us/04.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></a>
                        <div class="iq-portfolio-content  text-center">
                          <div class="details-box clearfix">
                            <div class="consult-details">
                              <a href="/portfolio-detail">
                                <h5 class="text-hover"> Statistical Analysis</h5>
                              </a>
                              <p class="mb-0">
                                HTML
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 text-left align-self-center">
                    <div class="iq-masonry-item item design ">
                      <div class="iq-portfolio">
                        <a href="/portfolio-detail" class="iq-portfolio-img"><img width="1260" height="954" src="/assets/images/about-us/05.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></a>
                        <div class="iq-portfolio-content  text-center">
                          <div class="details-box clearfix">
                            <div class="consult-details">
                              <a href="/portfolio-detail">
                                <h5 class="text-hover"> Forecasting</h5>
                              </a>
                              <p class="mb-0">
                                Design
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 text-left align-self-center">
                    <div class="iq-masonry-item item photography ">
                      <div class="iq-portfolio">
                        <a href="/portfolio-detail" class="iq-portfolio-img"><img width="1260" height="954" src="/assets/images/about-us/04.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></a>
                        <div class="iq-portfolio-content  text-center">
                          <div class="details-box clearfix">
                            <div class="consult-details">
                              <a href="/portfolio-detail">
                                <h5 class="text-hover"> Predictive Modeling</h5>
                              </a>
                              <p class="mb-0">
                                Photography
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 text-left align-self-center">
                    <div class="iq-masonry-item item photography ">
                      <div class="iq-portfolio">
                        <a href="/portfolio-detail" class="iq-portfolio-img"><img width="1260" height="954" src="/assets/images/about-us/03.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></a>
                        <div class="iq-portfolio-content  text-center">
                          <div class="details-box clearfix">
                            <div class="consult-details">
                              <a href="/portfolio-detail">
                                <h5 class="text-hover"> Forecasting</h5>
                              </a>
                              <p class="mb-0">
                                Photography
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 text-left align-self-center">
                    <div class="iq-masonry-item item design photography ">
                      <div class="iq-portfolio">
                        <a href="/portfolio-detail" class="iq-portfolio-img"><img width="1260" height="954" src="/assets/images/about-us/02.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></a>
                        <div class="iq-portfolio-content  text-center">
                          <div class="details-box clearfix">
                            <div class="consult-details">
                              <a href="/portfolio-detail">
                                <h5 class="text-hover">Optimization</h5>
                              </a>
                              <p class="mb-0">
                                Photography
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 text-left align-self-center">
                    <div class="iq-masonry-item item design ">
                      <div class="iq-portfolio">
                        <a href="/portfolio-detail" class="iq-portfolio-img"><img width="1260" height="954" src="/assets/images/about-us/01.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></a>
                        <div class="iq-portfolio-content  text-center">
                          <div class="details-box clearfix">
                            <div class="consult-details">
                              <a href="/portfolio-detail">
                                <h5 class="text-hover">Predictive Modeling</h5>
                              </a>
                              <p class="mb-0">
                                Design
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div id="design" class="tab-pane">
                <div class="row">
                  <div class="col-lg-4 col-md-6 text-left align-self-center">
                    <div class="iq-masonry-item item design ">
                      <div class="iq-portfolio">
                        <a href="/portfolio-detail" class="iq-portfolio-img"><img width="1260" height="954" src="/assets/images/about-us/05.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></a>
                        <div class="iq-portfolio-content  text-center">
                          <div class="details-box clearfix">
                            <div class="consult-details">
                              <a href="/portfolio-detail">
                                <h5 class="text-hover"> Business Growth</h5>
                              </a>
                              <p class="mb-0">
                                Design
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 text-left align-self-center">
                    <div class="iq-masonry-item item design photography ">
                      <div class="iq-portfolio">
                        <a href="/portfolio-detail" class="iq-portfolio-img"><img width="1260" height="954" src="/assets/images/about-us/02.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></a>
                        <div class="iq-portfolio-content  text-center">
                          <div class="details-box clearfix">
                            <div class="consult-details">
                              <a href="/portfolio-detail">
                                <h5 class="text-hover"> Business Growth</h5>
                              </a>
                              <p class="mb-0">
                                Photography
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-lg-4 col-md-6 text-left align-self-center">
                    <div class="iq-masonry-item item design ">
                      <div class="iq-portfolio">
                        <a href="/portfolio-detail" class="iq-portfolio-img"><img width="1260" height="954" src="/assets/images/about-us/01.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></a>
                        <div class="iq-portfolio-content  text-center">
                          <div class="details-box clearfix">
                            <div class="consult-details">
                              <a href="/portfolio-detail">
                                <h5 class="text-hover"> Business Growth</h5>
                              </a>
                              <p class="mb-0">
                                Design
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div id="html" class="tab-pane">
                <div class="row">
                  <div class="col-lg-4 col-md-6 text-left align-self-center">
                    <div class="iq-masonry-item item html ">
                      <div class="iq-portfolio">
                        <a href="/portfolio-detail" class="iq-portfolio-img"><img width="1260" height="954" src="/assets/images/about-us/03.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></a>
                        <div class="iq-portfolio-content  text-center">
                          <div class="details-box clearfix">
                            <div class="consult-details">
                              <a href="/portfolio-detail">
                                <h5 class="text-hover"> Business Growth</h5>
                              </a>
                              <p class="mb-0">
                                HTML
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 text-left align-self-center">
                    <div class="iq-masonry-item item html ">
                      <div class="iq-portfolio">
                        <a href="/portfolio-detail" class="iq-portfolio-img"><img width="1260" height="954" src="/assets/images/about-us/04.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></a>
                        <div class="iq-portfolio-content  text-center">
                          <div class="details-box clearfix">
                            <div class="consult-details">
                              <a href="/portfolio-detail">
                                <h5 class="text-hover"> Business Growth</h5>
                              </a>
                              <p class="mb-0">
                                HTML
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div id="photography" class="tab-pane">
                <div class="row">
                  <div class="col-lg-4 col-md-6 text-left align-self-center">
                    <div class="iq-masonry-item item photography ">
                      <div class="iq-portfolio">
                        <a href="/portfolio-detail" class="iq-portfolio-img"><img width="1260" height="954" src="/assets/images/about-us/04.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></a>
                        <div class="iq-portfolio-content  text-center">
                          <div class="details-box clearfix">
                            <div class="consult-details">
                              <a href="/portfolio-detail">
                                <h5 class="text-hover"> Business Growth</h5>
                              </a>
                              <p class="mb-0">
                                Photography
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 text-left align-self-center">
                    <div class="iq-masonry-item item photography ">
                      <div class="iq-portfolio">
                        <a href="/portfolio-detail" class="iq-portfolio-img"><img width="1260" height="954" src="/assets/images/about-us/03.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></a>
                        <div class="iq-portfolio-content  text-center">
                          <div class="details-box clearfix">
                            <div class="consult-details">
                              <a href="/portfolio-detail">
                                <h5 class="text-hover"> Business Growth</h5>
                              </a>
                              <p class="mb-0">
                                Photography
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 text-left align-self-center">
                    <div class="iq-masonry-item item design photography ">
                      <div class="iq-portfolio">
                        <a href="/portfolio-detail" class="iq-portfolio-img"><img width="1260" height="954" src="/assets/images/about-us/02.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></a>
                        <div class="iq-portfolio-content  text-center">
                          <div class="details-box clearfix">
                            <div class="consult-details">
                              <a href="/portfolio-detail">
                                <h5 class="text-hover"> Business Growth</h5>
                              </a>
                              <p class="mb-0">
                                Photography
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div id="video" class="tab-pane">
                <div class="row">
                  <div class="col-lg-4 col-md-6 text-left align-self-center">
                    <div class="iq-masonry-item item video ">
                      <div class="iq-portfolio">
                        <a href="/portfolio-detail" class="iq-portfolio-img"><img width="1260" height="954" src="/assets/images/about-us/01.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></a>
                        <div class="iq-portfolio-content  text-center">
                          <div class="details-box clearfix">
                            <div class="consult-details">
                              <a href="/portfolio-detail">
                                <h5 class="text-hover"> Business Growth</h5>
                              </a>
                              <p class="mb-0">
                                Video
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {
  name: 'Portfolio'
}
</script>
