// src/react/components/home-section/landing-page9/about/index.js
import React from 'react';

import {  SectionTitle, AdressSection} from '../../../xamin';
import Link from 'next/link';
import Image from 'next/image';

import img from "../../../../public/assets/images/about-us/19.png"
class   Index extends React.Component {
    constructor(props) {
        super(props);
        this.state={
           
            checkList:[
                {
                    icon:"fa fa-home mr-2",
                    heading:"Location",
                    text:"1234 North Avenue Luke Lane, South Bend, IN 360001",
                    class:"list-inline"
                },
                {
                    icon:"fa fa-phone mr-2",
                    heading:"Phone",
                    text:"+0123456789",
                    class:"list-inline",
                },
                {
                    icon:"fa fa-envelope mr-2",
                    heading:"Email",
                    text:"support@iqnonicthemes.com",
                    class:"list-inline"
                },
                {
                    icon:"fa fa-address-book-o",
                    heading: "Age",
                    text:" 31 Years",
                    class:"list-inline"
                },

              
            ],
        }
    }

    render() {
        const list = this.state.checkList;
        return (
            <>
              <section>
                  <div className="container">
                      <div className="row">
                          <div className="col-lg-5 col-md-5 col-sm-12">
                              <Image width="537" height="750" src={img} className="attachment-full" alt="about-us"  sizes="100vw" />
                          </div>
                          <div className="col-lg-7 col-md-7 col-sm-12">
                                <SectionTitle
                                    className={"title-box wow fadeInUp text-left"}
                                    spanclass={"title-design"}
                                    link={"ABOUT ME"}
                                    title={"I'm Professional Data Scientist having 10 Years Of Experience"}
                                    subTitle={"Consectetur fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters"}
                                />
                                <ul className="iq-address">
                                    
                                { list.map((item, index) => (
                                    <AdressSection 
                                        key={'about-'+index}
                                    icon ={item.icon}
                                    heading ={item.heading}
                                    text ={ item.text}
                                    className={item.class}
                                    />

                                 )) }
                                </ul>
                                <div className=" text-left  "><Link className="button blue-btn button-icon" href="#"><span className="btn-effect"> Download CV</span></Link></div>
                          </div>
                      </div>

                  </div>
              </section>
            </>
        );
    }
}

export default Index;

// src/vue/components/LandingPage16/About.vue
<template>
  <section class="position-relative overflow-hidden">
    <div class="container">
      <div class="row">
        <div class="col-lg-5">
          <div class="iq-higher-edu">
            <img src="/assets/images/others/02.png" class="img-fluid" alt="">
          </div>
        </div>
        <div class="col-lg-7 wow fadeInUp align-items-center">
          <div class="title-box wow fadeInUp  text-left">
            <span class="title-design">About me</span><h2>Improving Higher Education</h2><p>Consectetur fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.</p>
          </div>

          <ul class="iq-about-edu">
            <li><a><span class="header">Identify </span><span class="content">– With the formalized knowledge discovery models in Data Science, it is possible to identify data with the to produce better results.</span></a></li>
            <li class="list-inline">
              <a href="tel:+0123456789"><span class="header">Coordinate </span><span class="content">– A data platform will treat its users with a zero bias, meaning that there will not be any bias in the evaluation of student performance.</span></a>
            </li>
            <li class="list-inline">
              <a href="mailto:support@iqnonicthemes.com"><span class="header">Measure </span><span class="content">– Data science can be useful for analysing and measuring the industrial patterns and help the course creators to imbibe useful topics.</span></a>
            </li>
            <li class="list-inline">
              <a><span class="header">Unify </span><span class="content">– Data science is a powerful, web-based intelligence tool that provides various toolsets for reporting events through interactive visualizations.</span></a>
            </li>
          </ul>

          <div class=" text-left  mt-4">
            <a class="button blue-btn button-icon" href="/landing-page-16"><span class="btn-effect"> Read More</span></a>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {
  name: 'About'
}
</script>>
