// src/vue/components/LandingPage8/Client.vue
<template>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="title-box wow fadeInUp text-center">
            <span class="title-design">TRUSTED BY OVER 26,000 FORWARD - THINKING COMPANIES </span>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="owl-carousel owl-loaded owl-drag"
                data-dots="false"
                data-nav="false"
                data-items="6"
                data-items-laptop="4"
                data-items-tab="3"
                data-items-mobile="2"
                data-items-mobile-sm="1"
                data-dots-mobile="true"
                data-autoplay="true"
                data-loop="true"
                data-margin="30"
              >
                <div v-for="(item,index) in list" :key="index" class="item">
                  <div class="clients-box">
                    <img class="img-fluid client-img" :src="item.image" alt="image0">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {
  name: 'Client',
  data(){
    return{
      list:[
        {
          image : '/assets/images/partners/1.png'
        },
        {
          image : '/assets/images/partners/2.png'
        },
        {
          image : '/assets/images/partners/3.png'
        },
        {
          image : '/assets/images/partners/4.png'
        },
        {
          image : '/assets/images/partners/5.png'
        },
        {
          image : '/assets/images/partners/1.png'
        }
      ]
    }
  }
}
</script>

// src/react/components/pages-section/client/index.js
import React from 'react';

import { AboutStyle, SectionTitle} from '../../xamin';
import Link from 'next/link';
import Image from 'next/image';

const Cards = (props) => {
    const cardList = props.cardList;
    return cardList.map((card, index) => (
                <div key ={index} className="col-lg-2 col-md-3 col-sm-6 text-center "> 
                   <Link className="clients-block wow fadeIn" data-wow-delay="0.6s" href="#"> 
                        <Image className="img-fluid" src={card.img} alt="image0" />
                   </Link>
                </div>
    ));
};
class Index extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            cardData: [
                {
                    img:  require("../../../public/assets/images/partners/1.png"),
                    
                    
                },
                {
                    img:  require("../../../public/assets/images/partners/2.png"),
                   
                    
                },
                {
                    img:  require("../../../public/assets/images/partners/4.png"),
                    
                    
                },
                {
                    img:  require("../../../public/assets/images/partners/5.png"),
                    
                    
                }, {
                    img:  require("../../../public/assets/images/partners/1.png"),
                    
                    
                }, {
                    img:  require("../../../public/assets/images/partners/2.png"),
                    
                    
                }, {
                    img:  require("../../../public/assets/images/partners/3.png"),
                    
                    
                }, {
                    img:  require("../../../public/assets/images/partners/4.png"),
                    
                    
                }, {
                    img:  require("../../../public/assets/images/partners/5.png"),
                    
                    
                }, {
                    img:  require("../../../public/assets/images/partners/1.png"),
                    
                    
                }, {
                    img:  require("../../../public/assets/images/partners/3.png"),
                    
                    
                }, {
                    img:  require("../../../public/assets/images/partners/2.png"),
                    
                    
                }, {
                    img:  require("../../../public/assets/images/partners/4.png"),
                    
                    
                }, {
                    img:  require("../../../public/assets/images/partners/1.png"),
                    
                    
                }, {
                    img:  require("../../../public/assets/images/partners/2.png"),
                    
                    
                }, {
                    img:  require("../../../public/assets/images/partners/3.png"),
                    
                    
                }, {
                    img:  require("../../../public/assets/images/partners/5.png"),
                    
                    
                }, {
                    img:  require("../../../public/assets/images/partners/4.png"),
                    
                    
                },
            ]
        }
    }

    render() {
     
        return (
            <>
             <section>
                <div className="container">
                    <div className="row xamin-bg">
                        <div className="col-sm-12">
                        <SectionTitle
                            link ="OUR CLIENTS"
                            title="All Our Great Clients"
                            className = "title-box wow fadeInUp text-center"
                            spanclassName="title-design"
                        />
                        </div>
                        <div className="col-sm-12 ">
                             <div className="row fancy-clients  wow fadeIn">
                                <Cards cardList={this.state.cardData} />
                            </div>
                        </div>
                    </div>
                </div>
                  
             </section>
              
            </>
        );
    }
}

export default Index;
